# Chapter 17

In [1]:
import pandas as pd
import statsmodels.api as sm
import numpy as np
from scipy import stats
from linearmodels.iv import IV2SLS

In [2]:
# Exercise 1
pntsprd = pd.read_stata("./stata/PNTSPRD.DTA")
X = sm.add_constant(pntsprd[["spread"]])
model = sm.OLS(pntsprd.favwin, X, missing="drop").fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 favwin   R-squared:                       0.111
Model:                            OLS   Adj. R-squared:                  0.109
Method:                 Least Squares   F-statistic:                     68.57
Date:                Thu, 18 Aug 2022   Prob (F-statistic):           9.32e-16
Time:                        17:52:41   Log-Likelihood:                -279.29
No. Observations:                 553   AIC:                             562.6
Df Residuals:                     551   BIC:                             571.2
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.5769      0.028     20.434      0.000       0.521       0.632
spread         0.0194      0.002      8.281      0.000       0.015       0.024
==============================================================================
Omnibus:                       86.055   Durbin-Watson:                   2.112
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               94.402
Skew:                          -0.956   Prob(JB):                     3.17e-21
Kurtosis:                       2.336   Cond. No.                         20.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [3]:
model.t_test("const = 0.5")

<class 'statsmodels.stats.contrast.ContrastResults'>
                             Test for Constraints                             
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
c0             0.5769      0.028      2.725      0.007       0.521       0.632

In [4]:
model = sm.OLS(pntsprd.favwin, X, missing="drop").fit(cov_type="HC3")
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 favwin   R-squared:                       0.111
Model:                            OLS   Adj. R-squared:                  0.109
Method:                 Least Squares   F-statistic:                     100.8
Date:                Thu, 18 Aug 2022   Prob (F-statistic):           6.80e-22
Time:                        17:52:41   Log-Likelihood:                -279.29
No. Observations:                 553   AIC:                             562.6
Df Residuals:                     551   BIC:                             571.2
Df Model:                           1                                         
Covariance Type:                  HC3                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.5769      0.032     18.190      0.000       0.515       0.639
spread         0.0194      0.002     10.040      0.000       0.016       0.023
==============================================================================
Omnibus:                       86.055   Durbin-Watson:                   2.112
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               94.402
Skew:                          -0.956   Prob(JB):                     3.17e-21
Kurtosis:                       2.336   Cond. No.                         20.0
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
"""

In [5]:
model.predict([1, 10])

array([0.77060438])

In [6]:
model.t_test("const = 0.5")

<class 'statsmodels.stats.contrast.ContrastResults'>
                             Test for Constraints                             
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
c0             0.5769      0.032      2.426      0.015       0.515       0.639

In [7]:
model = sm.Probit(pntsprd.favwin, X, missing="drop").fit()
model.summary()

Optimization terminated successfully.
         Current function value: 0.476604
         Iterations 6


<class 'statsmodels.iolib.summary.Summary'>
"""
                          Probit Regression Results                           
==============================================================================
Dep. Variable:                 favwin   No. Observations:                  553
Model:                         Probit   Df Residuals:                      551
Method:                           MLE   Df Model:                            1
Date:                Thu, 18 Aug 2022   Pseudo R-squ.:                  0.1294
Time:                        17:52:41   Log-Likelihood:                -263.56
converged:                       True   LL-Null:                       -302.75
Covariance Type:            nonrobust   LLR p-value:                 8.521e-19
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0106      0.104     -0.102      0.919      -0.214       0.193
spread         0.0925      0.012      7.591      0.000       0.069       0.116
==============================================================================
"""

In [8]:
model.t_test("const = 0")

<class 'statsmodels.stats.contrast.ContrastResults'>
                             Test for Constraints                             
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
c0            -0.0106      0.104     -0.102      0.919      -0.214       0.193

In [9]:
model.predict([1, 10])

array([0.81965134])

In [10]:
X = sm.add_constant(pntsprd[["spread", "favhome", "fav25", "und25"]])
model = sm.Probit(pntsprd.favwin, X, missing="drop").fit()
model.summary()

Optimization terminated successfully.
         Current function value: 0.474940
         Iterations 6


<class 'statsmodels.iolib.summary.Summary'>
"""
                          Probit Regression Results                           
==============================================================================
Dep. Variable:                 favwin   No. Observations:                  553
Model:                         Probit   Df Residuals:                      548
Method:                           MLE   Df Model:                            4
Date:                Thu, 18 Aug 2022   Pseudo R-squ.:                  0.1325
Time:                        17:52:42   Log-Likelihood:                -262.64
converged:                       True   LL-Null:                       -302.75
Covariance Type:            nonrobust   LLR p-value:                 1.567e-16
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0552      0.129     -0.429      0.668      -0.308       0.197
spread         0.0879      0.013      6.787      0.000       0.063       0.113
favhome        0.1486      0.137      1.084      0.278      -0.120       0.417
fav25          0.0031      0.159      0.019      0.985      -0.308       0.314
und25         -0.2198      0.251     -0.877      0.380      -0.711       0.271
==============================================================================
"""

In [11]:
model.wald_test("favhome = fav25 = und25 = 0", scalar=True) # Not LR but seems to work?

<class 'statsmodels.stats.contrast.ContrastResults'>
<Wald test (chi2): statistic=1.8440186856438163, p-value=0.605403142010621, df_denom=3>

C1.i When the spread is zero neither team is favoured to win, and so it should follow that the probability is even (50%).

C1.ii We reject the null hypothesis for both the ordinary and HC3 errors, at least at the 5% level (1% for the unadjusted errors, but given that it is the linear probability model, it is more appropriate to consider the robust errors). In either case, we reject the null that the constant is 0.5.

C1.iii Spread is statistically singificant under both sets of errors. The estimated probability under the linear probability model when spread = 10 is approximately 77%.

C1.iv We do not reject the null hypothesis that the constant is zero. This is the equivalent to our earlier test under the linear probability model, but takes into account that we are running a probit model. If the spread is 0 and the constant is 0 then we have the CDF of the normal distribution at 0, or, 0.5.

C1.v The probability under the probit model is a little higher at 82%

C1.vi The new variables are not jointly significant. The other factors do not anything to predicting the outcome once spread is accounted for.

In [12]:
# Exercise 2
loanapp = pd.read_stata("./stata/loanapp.dta")
X = sm.add_constant(loanapp[["white"]])
model = sm.OLS(loanapp.approve, X, missing="drop").fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                approve   R-squared:                       0.049
Model:                            OLS   Adj. R-squared:                  0.048
Method:                 Least Squares   F-statistic:                     102.2
Date:                Thu, 18 Aug 2022   Prob (F-statistic):           1.81e-23
Time:                        17:52:42   Log-Likelihood:                -555.54
No. Observations:                1989   AIC:                             1115.
Df Residuals:                    1987   BIC:                             1126.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.7078      0.018     38.806      0.000       0.672       0.744
white          0.2006      0.020     10.111      0.000       0.162       0.240
==============================================================================
Omnibus:                      801.085   Durbin-Watson:                   2.002
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2394.523
Skew:                          -2.161   Prob(JB):                         0.00
Kurtosis:                       6.197   Cond. No.                         4.90
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [13]:
print(model.predict([1, 1]))
print(model.predict([1, 0]))

[0.90838786]
[0.70779221]


In [14]:
model = sm.Probit(loanapp.approve, X, missing="drop").fit()
model.summary()

Optimization terminated successfully.
         Current function value: 0.352377
         Iterations 6


<class 'statsmodels.iolib.summary.Summary'>
"""
                          Probit Regression Results                           
==============================================================================
Dep. Variable:                approve   No. Observations:                 1989
Model:                         Probit   Df Residuals:                     1987
Method:                           MLE   Df Model:                            1
Date:                Thu, 18 Aug 2022   Pseudo R-squ.:                 0.05331
Time:                        17:52:42   Log-Likelihood:                -700.88
converged:                       True   LL-Null:                       -740.35
Covariance Type:            nonrobust   LLR p-value:                 6.408e-19
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.5469      0.075      7.251      0.000       0.399       0.695
white          0.7839      0.087      9.041      0.000       0.614       0.954
==============================================================================
"""

In [15]:
print(model.predict([1, 1]))
print(model.predict([1, 0]))

[0.90838786]
[0.70779221]


In [16]:
X = sm.add_constant(loanapp[["white", "hrat", "obrat", "loanprc", "unem", "male", "married", "dep", "sch", "cosign", "chist", "pubrec", "mortlat1", "mortlat2", "vr"]])
model = sm.Probit(loanapp.approve, X, missing="drop").fit()
model.summary()

Optimization terminated successfully.
         Current function value: 0.304551
         Iterations 6


<class 'statsmodels.iolib.summary.Summary'>
"""
                          Probit Regression Results                           
==============================================================================
Dep. Variable:                approve   No. Observations:                 1971
Model:                         Probit   Df Residuals:                     1955
Method:                           MLE   Df Model:                           15
Date:                Thu, 18 Aug 2022   Pseudo R-squ.:                  0.1866
Time:                        17:52:42   Log-Likelihood:                -600.27
converged:                       True   LL-Null:                       -737.98
Covariance Type:            nonrobust   LLR p-value:                 7.014e-50
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.0623      0.313      6.585      0.000       1.449       2.676
white          0.5203      0.097      5.366      0.000       0.330       0.710
hrat           0.0079      0.007      1.131      0.258      -0.006       0.022
obrat         -0.0277      0.006     -4.578      0.000      -0.040      -0.016
loanprc       -1.0120      0.237     -4.266      0.000      -1.477      -0.547
unem          -0.0367      0.017     -2.099      0.036      -0.071      -0.002
male          -0.0370      0.110     -0.337      0.736      -0.252       0.178
married        0.2657      0.094      2.820      0.005       0.081       0.450
dep           -0.0496      0.039     -1.269      0.204      -0.126       0.027
sch            0.0146      0.096      0.153      0.879      -0.173       0.202
cosign         0.0861      0.246      0.350      0.726      -0.396       0.568
chist          0.5853      0.096      6.098      0.000       0.397       0.773
pubrec        -0.7787      0.126     -6.165      0.000      -1.026      -0.531
mortlat1      -0.1876      0.253     -0.741      0.459      -0.684       0.308
mortlat2      -0.4944      0.327     -1.514      0.130      -1.134       0.146
vr            -0.2011      0.081     -2.467      0.014      -0.361      -0.041
==============================================================================
"""

In [17]:
X_pred = X.dropna()
X_pred["white"] = 0
prob_avg = model.predict(X_pred).mean()
X_pred["white"] = 1
model.predict(X_pred).mean() - prob_avg

/tmp/ipykernel_3660/89657284.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_pred["white"] = 0
/tmp/ipykernel_3660/89657284.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_pred["white"] = 1


0.104224483076233

In [18]:
model = sm.Logit(loanapp.approve, X, missing="drop").fit()
model.summary()

Optimization terminated successfully.
         Current function value: 0.304666
         Iterations 7


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                approve   No. Observations:                 1971
Model:                          Logit   Df Residuals:                     1955
Method:                           MLE   Df Model:                           15
Date:                Thu, 18 Aug 2022   Pseudo R-squ.:                  0.1863
Time:                        17:52:44   Log-Likelihood:                -600.50
converged:                       True   LL-Null:                       -737.98
Covariance Type:            nonrobust   LLR p-value:                 8.693e-50
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          3.8017      0.595      6.393      0.000       2.636       4.967
white          0.9378      0.173      5.424      0.000       0.599       1.277
hrat           0.0133      0.013      1.030      0.303      -0.012       0.039
obrat         -0.0530      0.011     -4.701      0.000      -0.075      -0.031
loanprc       -1.9050      0.460     -4.137      0.000      -2.807      -1.002
unem          -0.0666      0.033     -2.029      0.042      -0.131      -0.002
male          -0.0664      0.206     -0.322      0.748      -0.471       0.338
married        0.5033      0.178      2.827      0.005       0.154       0.852
dep           -0.0907      0.073     -1.237      0.216      -0.234       0.053
sch            0.0412      0.178      0.231      0.817      -0.308       0.391
cosign         0.1321      0.446      0.296      0.767      -0.742       1.006
chist          1.0666      0.171      6.230      0.000       0.731       1.402
pubrec        -1.3407      0.217     -6.168      0.000      -1.767      -0.915
mortlat1      -0.3099      0.464     -0.669      0.504      -1.218       0.599
mortlat2      -0.8947      0.569     -1.574      0.116      -2.009       0.220
vr            -0.3498      0.154     -2.276      0.023      -0.651      -0.049
==============================================================================
"""

In [19]:
X_pred = X.dropna()
X_pred["white"] = 0
log_avg = model.predict(X_pred).mean()
X_pred["white"] = 1
model.predict(X_pred).mean() - log_avg

/tmp/ipykernel_3660/1197556308.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_pred["white"] = 0
/tmp/ipykernel_3660/1197556308.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_pred["white"] = 1


0.10087064751405628

C2.i Estimates above. Both the Probit and LPM are identical.

C2.ii White is positive and significant, suggesting there is evidence of discrimination.

C2.iii The coefficient on white is notably higher but still positive and significant.

C2.iv The size of the effect under probit is 10.4%, while the logit effect is about 10.1%

In [20]:
# Exercise 3
# Statsmodels is not equipped for Tobit yet.
from py4etrics.tobit import Tobit
fringe = pd.read_stata("./stata/FRINGE.DTA")
print("Percentage of workers with pension = 0:", ((fringe.pension == 0).sum() / fringe.shape[0]) * 100)
fringe[fringe.pension > 0]["pension"].describe()

Percentage of workers with pension = 0: 27.92207792207792


count     444.000000
mean      905.043396
std       550.369629
min         7.280000
25%       421.777504
50%       813.940002
75%      1264.680054
max      2880.270020
Name: pension, dtype: float64

In [21]:
X = sm.add_constant(fringe[["exper", "age", "tenure", "educ", "depends", "married", "white", "male"]])
cens = np.zeros(fringe.shape[0])
cens[fringe.pension == 0 ] = -1
model = Tobit(fringe.pension, X, cens = cens, missing="drop").fit()
model.summary()

Optimization terminated successfully.
         Current function value: 5.962603
         Iterations: 4057
         Function evaluations: 5671


<class 'statsmodels.iolib.summary.Summary'>
"""
                              Tobit Regression Results                             
===================================================================================
Dep. Variable:                     pension   Pseudo R-squ:                    0.025
Method:                 Maximum Likelihood   Log-Likelihood:                -3673.0
No. Observations:                      616   LL-Null:                       -3765.3
No. Uncensored Obs:                    444   LL-Ratio:                        184.7
No. Left-censored Obs:                 172   LLR p-value:                     0.000
No. Right-censored Obs:                  0   AIC:                            7363.9
Df Residuals:                          607   BIC:                            7403.7
Df Model:                                8   Covariance Type:             nonrobust
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1252.4287    219.076     -5.717      0.000   -1681.809    -823.048
exper          5.2035      6.009      0.866      0.387      -6.575      16.982
age           -4.6389      5.711     -0.812      0.417     -15.832       6.554
tenure        36.0239      4.565      7.892      0.000      27.078      44.970
educ          93.2126     10.892      8.558      0.000      71.865     114.560
depends       35.2846     21.918      1.610      0.107      -7.673      78.242
married       53.6886     71.734      0.748      0.454     -86.907     194.285
white        144.0855    102.079      1.412      0.158     -55.985     344.156
male         308.1504     69.893      4.409      0.000     171.163     445.137
Log(Sigma)     6.5188      0.036    183.014      0.000       6.449       6.589
==============================================================================
"""

In [22]:
# Sadly predict is not implemented. TBD for (iii)

In [23]:
X = sm.add_constant(fringe[["exper", "age", "tenure", "educ", "depends", "married", "white", "male", "union"]])
model = Tobit(fringe.pension, X, cens = cens, missing="drop").fit()
model.summary()

Optimization terminated successfully.
         Current function value: 5.922973
         Iterations: 5137
         Function evaluations: 7166


<class 'statsmodels.iolib.summary.Summary'>
"""
                              Tobit Regression Results                             
===================================================================================
Dep. Variable:                     pension   Pseudo R-squ:                    0.031
Method:                 Maximum Likelihood   Log-Likelihood:                -3648.6
No. Observations:                      616   LL-Null:                       -3765.3
No. Uncensored Obs:                    444   LL-Ratio:                        233.5
No. Left-censored Obs:                 172   LLR p-value:                     0.000
No. Right-censored Obs:                  0   AIC:                            7317.1
Df Residuals:                          606   BIC:                            7361.3
Df Model:                                9   Covariance Type:             nonrobust
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1571.5064    218.542     -7.191      0.000   -1999.841   -1143.172
exper          4.3935      5.831      0.754      0.451      -7.035      15.822
age           -1.6535      5.556     -0.298      0.766     -12.542       9.235
tenure        28.7784      4.505      6.388      0.000      19.949      37.608
educ         106.8277     10.773      9.916      0.000      85.714     127.942
depends       41.4662     21.214      1.955      0.051      -0.113      83.045
married       19.7455     69.501      0.284      0.776    -116.474     155.965
white        159.2973     98.967      1.610      0.107     -34.675     353.270
male         257.2457     68.021      3.782      0.000     123.927     390.564
union        439.0460     62.488      7.026      0.000     316.571     561.521
Log(Sigma)     6.4814      0.035    182.693      0.000       6.412       6.551
==============================================================================
"""

In [24]:
X = sm.add_constant(fringe[["exper", "age", "tenure", "educ", "depends", "married", "white", "male", "union"]])
model = Tobit(fringe.peratio, X, cens = cens, missing="drop").fit()
model.summary()

Optimization terminated successfully.
         Current function value: -0.984603
         Iterations: 1223
         Function evaluations: 1699


<class 'statsmodels.iolib.summary.Summary'>
"""
                              Tobit Regression Results                             
===================================================================================
Dep. Variable:                     peratio   Pseudo R-squ:                   -0.146
Method:                 Maximum Likelihood   Log-Likelihood:                  606.5
No. Observations:                      616   LL-Null:                         529.3
No. Uncensored Obs:                    444   LL-Ratio:                        154.4
No. Left-censored Obs:                 172   LLR p-value:                     0.000
No. Right-censored Obs:                  0   AIC:                           -1193.0
Df Residuals:                          606   BIC:                           -1148.8
Df Model:                                9   Covariance Type:             nonrobust
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0523      0.014     -3.621      0.000      -0.081      -0.024
exper         -0.0003      0.000     -0.686      0.493      -0.001       0.000
age            0.0001      0.000      0.328      0.743      -0.001       0.001
tenure         0.0018      0.000      5.919      0.000       0.001       0.002
educ           0.0051      0.001      7.126      0.000       0.004       0.006
depends        0.0002      0.001      0.129      0.898      -0.003       0.003
married        0.0032      0.005      0.699      0.484      -0.006       0.012
white         -0.0017      0.007     -0.267      0.790      -0.015       0.011
male           0.0047      0.005      1.031      0.303      -0.004       0.014
union          0.0293      0.004      7.022      0.000       0.021       0.038
Log(Sigma)    -3.1278      0.036    -87.088      0.000      -3.198      -3.057
==============================================================================
"""

C3.i About 27% of the observations are qual to zero, and the range for positive values are 7.28 to 2,880.27. Tobit is appropriate here since a significant number of observations are zero, and the positive values are continuous over a wide range.

C3.ii Results above. Male is significant but white does not appear to be significant, though both are positive.

C3.iii Could not complete due to a lack of predict method and no estimate for $\sigma$.

C3.iv Results above. Union is positive (in fact the largest value) and significant.

C3.v Results above. The significance for both the white and male variables goes away, and white becomes negative. There is no evidence that gender or race have an effect on the pension-earnings ratio.

In [25]:
# Exercise 4
crime1 = pd.read_stata("./stata/CRIME1.DTA")
X = sm.add_constant(crime1[["pcnv", "pcnvsq", "avgsen", "tottime", "ptime86", "pt86sq", "qemp86", "inc86", "inc86sq", "black", "hispan", "born60"]])
# I'd rather not switch methods, but newton produces an error.
model = sm.Poisson(crime1.narr86, X, missing="drop").fit(method="basinhopping", maxiter=10000)
model.summary()

basinhopping step 0: f 28.2856
basinhopping step 1: f 28.2856 trial_f inf accepted 0  lowest_f 28.2856
basinhopping step 2: f 28.2856 trial_f inf accepted 0  lowest_f 28.2856
basinhopping step 3: f 0.795914 trial_f 0.795914 accepted 1  lowest_f 0.795914
found new global minimum on step 3 with function value 0.795914
basinhopping step 4: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 5: f 0.795914 trial_f 300.293 accepted 0  lowest_f 0.795914
basinhopping step 6: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 7: f 0.795914 trial_f 334.3 accepted 0  lowest_f 0.795914


/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/statsmodels/discrete/discrete_model.py:1243: RuntimeWarning: overflow encountered in exp
  L = np.exp(np.dot(X,params) + offset + exposure)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/statsmodels/discrete/discrete_model.py:1009: RuntimeWarning: overflow encountered in exp
  return stats.poisson.cdf(y, np.exp(X))
/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/

basinhopping step 8: f 0.795914 trial_f 0.795914 accepted 1  lowest_f 0.795914
basinhopping step 9: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 10: f 0.795914 trial_f 19.0603 accepted 0  lowest_f 0.795914
basinhopping step 11: f 0.795914 trial_f 460.158 accepted 0  lowest_f 0.795914
basinhopping step 12: f 0.795914 trial_f 0.795914 accepted 1  lowest_f 0.795914
basinhopping step 13: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 14: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 15: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 16: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914


/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/statsmodels/discrete/discrete_model.py:1243: RuntimeWarning: overflow encountered in exp
  L = np.exp(np.dot(X,params) + offset + exposure)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/statsmodels/discrete/discrete_model.py:1009: RuntimeWarning: overflow encountered in exp
  return stats.poisson.cdf(y, np.exp(X))
/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/

basinhopping step 17: f 0.795914 trial_f 286.661 accepted 0  lowest_f 0.795914
basinhopping step 18: f 0.795914 trial_f 0.795914 accepted 1  lowest_f 0.795914


/home/systemchalk/anaconda3/lib/python3.9/site-packages/scipy/optimize/linesearch.py:153: RuntimeWarning: invalid value encountered in double_scalars
  alpha1 = min(1.0, 1.01*2*(phi0 - old_phi0)/derphi0)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/scipy/optimize/linesearch.py:403: RuntimeWarning: invalid value encountered in double_scalars
  alpha1 = min(1.0, 1.01*2*(phi0 - old_phi0)/derphi0)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/statsmodels/discrete/discrete_model.py:1243: RuntimeWarning: overflow encountered in exp
  L = np.exp(np.dot(X,params) + offset + exposure)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/statsmodels/discrete/discrete_model.py:1009: RuntimeWarning: overflow encountered in exp
  return stats.poisson.cdf(y, np.exp(X))
/home/systemchalk/

basinhopping step 19: f 0.795914 trial_f 7.19542e+186 accepted 0  lowest_f 0.795914
basinhopping step 20: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 21: f 0.795914 trial_f 11.0581 accepted 0  lowest_f 0.795914
basinhopping step 22: f 0.795914 trial_f 49.381 accepted 0  lowest_f 0.795914
basinhopping step 23: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 24: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 25: f 0.795914 trial_f 321.533 accepted 0  lowest_f 0.795914
basinhopping step 26: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 27: f 0.795914 trial_f 101.896 accepted 0  lowest_f 0.795914


/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/statsmodels/discrete/discrete_model.py:1243: RuntimeWarning: overflow encountered in exp
  L = np.exp(np.dot(X,params) + offset + exposure)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/pyth

basinhopping step 28: f 0.795914 trial_f 47.8716 accepted 0  lowest_f 0.795914
basinhopping step 29: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 30: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 31: f 0.795914 trial_f 291.232 accepted 0  lowest_f 0.795914
basinhopping step 32: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 33: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 34: f 0.795914 trial_f 159.102 accepted 0  lowest_f 0.795914
basinhopping step 35: f 0.795914 trial_f 498.043 accepted 0  lowest_f 0.795914
basinhopping step 36: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 37: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 38: f 0.795914 trial_f 529.448 accepted 0  lowest_f 0.795914
basinhopping step 39: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 40: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basin

/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/statsmodels/discrete/discrete_model.py:1243: RuntimeWarning: overflow encountered in exp
  L = np.exp(np.dot(X,params) + offset + exposure)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/statsmodels/discrete/discrete_model.py:1009: RuntimeWarning: overflow encountered in exp
  return stats.poisson.cdf(y, np.exp(X))
/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/

basinhopping step 44: f 0.795914 trial_f 0.795914 accepted 1  lowest_f 0.795914
basinhopping step 45: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 46: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 47: f 0.795914 trial_f 382.585 accepted 0  lowest_f 0.795914
basinhopping step 48: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 49: f 0.795914 trial_f 415.311 accepted 0  lowest_f 0.795914
adaptive stepsize: acceptance rate 0.100000 target 0.500000 new stepsize 0.45 old stepsize 0.5
basinhopping step 50: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 51: f 0.795914 trial_f 402.764 accepted 0  lowest_f 0.795914


/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/statsmodels/discrete/discrete_model.py:1243: RuntimeWarning: overflow encountered in exp
  L = np.exp(np.dot(X,params) + offset + exposure)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/statsmodels/discrete/discrete_model.py:1009: RuntimeWarning: overflow encountered in exp
  return stats.poisson.cdf(y, np.exp(X))
/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/

basinhopping step 52: f 0.795914 trial_f 0.795914 accepted 1  lowest_f 0.795914
basinhopping step 53: f 0.795914 trial_f 0.795914 accepted 1  lowest_f 0.795914
basinhopping step 54: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 55: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 56: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 57: f 0.795914 trial_f 0.795914 accepted 1  lowest_f 0.795914
basinhopping step 58: f 0.795914 trial_f 381.312 accepted 0  lowest_f 0.795914


/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/statsmodels/discrete/discrete_model.py:1243: RuntimeWarning: overflow encountered in exp
  L = np.exp(np.dot(X,params) + offset + exposure)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/statsmodels/discrete/discrete_model.py:1243: RuntimeWarning: overflow encountered in exp
  L = np.exp(np.dot(X,params) + offset + exposure)
/home/systemchalk/anaconda3/lib/

basinhopping step 59: f 0.795914 trial_f 464.704 accepted 0  lowest_f 0.795914
basinhopping step 60: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 61: f 0.795914 trial_f 0.795914 accepted 1  lowest_f 0.795914
basinhopping step 62: f 0.795914 trial_f 203.263 accepted 0  lowest_f 0.795914
basinhopping step 63: f 0.795914 trial_f 291.951 accepted 0  lowest_f 0.795914
basinhopping step 64: f 0.795914 trial_f 0.795914 accepted 1  lowest_f 0.795914
basinhopping step 65: f 0.795914 trial_f 984.735 accepted 0  lowest_f 0.795914
basinhopping step 66: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 67: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 68: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 69: f 0.795914 trial_f 319.186 accepted 0  lowest_f 0.795914
basinhopping step 70: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914


/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/statsmodels/discrete/discrete_model.py:1243: RuntimeWarning: overflow encountered in exp
  L = np.exp(np.dot(X,params) + offset + exposure)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/statsmodels/discrete/discrete_model.py:1243: RuntimeWarning: overflow encountered in exp
  L = np.exp(np.dot(X,params) + offset + exposure)
/home/systemchalk/anaconda3/lib/

basinhopping step 71: f 0.795914 trial_f 0.795914 accepted 1  lowest_f 0.795914
basinhopping step 72: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 73: f 0.795914 trial_f 1.65847 accepted 0  lowest_f 0.795914
basinhopping step 74: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 75: f 0.795914 trial_f 501.07 accepted 0  lowest_f 0.795914
basinhopping step 76: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 77: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 78: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 79: f 0.795914 trial_f 52.1791 accepted 0  lowest_f 0.795914
basinhopping step 80: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 81: f 0.795914 trial_f 254.362 accepted 0  lowest_f 0.795914
basinhopping step 82: f 0.795914 trial_f 213.589 accepted 0  lowest_f 0.795914
basinhopping step 83: f 0.795914 trial_f 36.0648 accepted 0  lowest_f 0.7959

/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/statsmodels/discrete/discrete_model.py:1243: RuntimeWarning: overflow encountered in exp
  L = np.exp(np.dot(X,params) + offset + exposure)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/statsmodels/discrete/discrete_model.py:1009: RuntimeWarning: overflow encountered in exp
  return stats.poisson.cdf(y, np.exp(X))
/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/

basinhopping step 96: f 0.795914 trial_f 1144.06 accepted 0  lowest_f 0.795914
basinhopping step 97: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 98: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
basinhopping step 99: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914
adaptive stepsize: acceptance rate 0.110000 target 0.500000 new stepsize 0.405 old stepsize 0.45
basinhopping step 100: f 0.795914 trial_f inf accepted 0  lowest_f 0.795914


/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/statsmodels/discrete/discrete_model.py:1243: RuntimeWarning: overflow encountered in exp
  L = np.exp(np.dot(X,params) + offset + exposure)
/home/systemchalk/anaconda3/lib/python3.9/site-packages/statsmodels/discrete/discrete_model.py:1009: RuntimeWarning: overflow encountered in exp
  return stats.poisson.cdf(y, np.exp(X))


<class 'statsmodels.iolib.summary.Summary'>
"""
                          Poisson Regression Results                          
==============================================================================
Dep. Variable:                 narr86   No. Observations:                 2725
Model:                        Poisson   Df Residuals:                     2712
Method:                           MLE   Df Model:                           12
Date:                Thu, 18 Aug 2022   Pseudo R-squ.:                  0.1118
Time:                        17:53:04   Log-Likelihood:                -2168.9
converged:                       True   LL-Null:                       -2441.9
Covariance Type:            nonrobust   LLR p-value:                3.342e-109
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.7099      0.070    -10.107      0.000      -0.848      -0.572
pcnv           1.1531      0.282      4.085      0.000       0.600       1.706
pcnvsq        -1.7951      0.307     -5.844      0.000      -2.397      -1.193
avgsen        -0.0256      0.021     -1.191      0.234      -0.068       0.017
tottime        0.0122      0.016      0.771      0.441      -0.019       0.043
ptime86        0.6837      0.091      7.495      0.000       0.505       0.862
pt86sq        -0.1034      0.016     -6.390      0.000      -0.135      -0.072
qemp86         0.0230      0.033      0.703      0.482      -0.041       0.087
inc86         -0.0121      0.002     -6.608      0.000      -0.016      -0.008
inc86sq     2.068e-05   6.14e-06      3.368      0.001    8.65e-06    3.27e-05
black          0.5914      0.074      7.953      0.000       0.446       0.737
hispan         0.4220      0.075      5.640      0.000       0.275       0.569
born60        -0.0929      0.064     -1.447      0.148      -0.219       0.033
==============================================================================
"""

In [26]:
sigma_sq = (((model.resid**2) / model.predict()).sum() / model.df_resid)
sigma_sq

1.3911544523492008

In [27]:
np.sqrt(sigma_sq)

1.1794721074909744

In [28]:
quasi_llr = -2 * (-2248.76 - model.llf) / sigma_sq
quasi_llr

114.85931184611484

In [29]:
stats.chi2.pdf(quasi_llr, 3)

4.893397613363349e-25

C4.i Results above.

C4.ii $\hat{\sigma}^2$ is 1.39 which would suggest overidspersion. The standard errors should be multiplied by $\hat{\sigma}$.

C4.iii Work above, but the quasi-likelihood ratio for joint significance has a test statistic of about 114.9 resulting in a p-value smaller than any reasonable threshold we could set. The quadratic terms are jointly significant.

In [30]:
# Exercise 5
fertil1 = pd.read_stata("./stata/FERTIL1.DTA")
X = sm.add_constant(fertil1[["educ", "age", "agesq", "black", "east", "northcen", "west", "farm", "othrural",
                             "town", "smcity", "y74", "y76", "y78", "y80", "y82", "y84"]])
model = sm.Poisson(fertil1.kids, X, missing="drop").fit()
model.summary()

Optimization terminated successfully.
         Current function value: 1.833682
         Iterations 8


<class 'statsmodels.iolib.summary.Summary'>
"""
                          Poisson Regression Results                          
==============================================================================
Dep. Variable:                   kids   No. Observations:                 1129
Model:                        Poisson   Df Residuals:                     1111
Method:                           MLE   Df Model:                           17
Date:                Thu, 18 Aug 2022   Pseudo R-squ.:                 0.03424
Time:                        17:53:04   Log-Likelihood:                -2070.2
converged:                       True   LL-Null:                       -2143.6
Covariance Type:            nonrobust   LLR p-value:                 1.033e-22
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -3.0605      1.211     -2.528      0.011      -5.433      -0.688
educ          -0.0482      0.007     -6.667      0.000      -0.062      -0.034
age            0.2045      0.055      3.734      0.000       0.097       0.312
agesq         -0.0022      0.001     -3.612      0.000      -0.003      -0.001
black          0.3603      0.061      5.900      0.000       0.241       0.480
east           0.0878      0.053      1.667      0.096      -0.015       0.191
northcen       0.1417      0.048      2.983      0.003       0.049       0.235
west           0.0795      0.066      1.211      0.226      -0.049       0.208
farm          -0.0148      0.058     -0.258      0.796      -0.128       0.098
othrural      -0.0573      0.069     -0.828      0.407      -0.193       0.078
town           0.0307      0.049      0.632      0.528      -0.065       0.126
smcity         0.0741      0.062      1.204      0.229      -0.047       0.195
y74            0.0933      0.063      1.479      0.139      -0.030       0.217
y76           -0.0288      0.068     -0.426      0.670      -0.161       0.104
y78           -0.0157      0.069     -0.228      0.819      -0.150       0.119
y80           -0.0197      0.069     -0.285      0.776      -0.155       0.116
y82           -0.1926      0.067     -2.853      0.004      -0.325      -0.060
y84           -0.2144      0.069     -3.086      0.002      -0.351      -0.078
==============================================================================
"""

In [31]:
np.exp(model.params["black"]) - 1

0.4338276339995719

In [32]:
sigma_sq = (((model.resid**2) / model.predict()).sum() / model.df_resid)
np.sqrt(sigma_sq)

0.9441815299783197

In [33]:
np.corrcoef(model.predict(),(model.model.endog))[0,1] ** 2

0.12089324731196875

C5.i Results above. The coefficient on y82 indicates that women had about 19.3% fewer children in that period (i.e. fertility was about 20% lower in 1982).

C5.ii After the adjustment the value is 0.434 suggesting that black women's fertility was 43.4% higher.

C5.iii $\hat{\sigma}^2$ is 0.944 and so if anything there is underdispersion.

C5.iv The squared correlation (R-squared) is 0.1209. This is a little smaller than the R-squared in Table 13.1 (0.1295)

In [34]:
# Exercise 6
recid = pd.read_excel("./excel/recid.xls")
                      
recid.columns = ["black", "alcohol", "drugs", "super", "married", "felon", "workprg",
                 "property", "person", "priors", "educ", "rules", "age", "tserved",
                 "follow", "durat", "cens", "ldurat"]
recid = recid[recid.cens == 0]
X = sm.add_constant(recid[["workprg", "priors", "tserved", "felon", "alcohol", "drugs", "black", "married", "educ", "age"]])
model = sm.OLS(recid.ldurat, X, missing="drop").fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 ldurat   R-squared:                       0.071
Model:                            OLS   Adj. R-squared:                  0.054
Method:                 Least Squares   F-statistic:                     4.125
Date:                Thu, 18 Aug 2022   Prob (F-statistic):           1.66e-05
Time:                        17:53:05   Log-Likelihood:                -722.41
No. Observations:                 552   AIC:                             1467.
Df Residuals:                     541   BIC:                             1514.
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          3.0010      0.244     12.307      0.000       2.522       3.480
workprg        0.0923      0.083      1.116      0.265      -0.070       0.255
priors        -0.0484      0.014     -3.444      0.001      -0.076      -0.021
tserved       -0.0068      0.002     -3.496      0.001      -0.011      -0.003
felon          0.1187      0.103      1.150      0.251      -0.084       0.321
alcohol       -0.2180      0.097     -2.247      0.025      -0.409      -0.027
drugs          0.0178      0.089      0.199      0.842      -0.157       0.193
black         -0.0009      0.082     -0.010      0.992      -0.162       0.161
married        0.2389      0.099      2.420      0.016       0.045       0.433
educ          -0.0195      0.019     -1.028      0.304      -0.057       0.018
age            0.0005      0.000      1.264      0.207      -0.000       0.001
==============================================================================
Omnibus:                       34.768   Durbin-Watson:                   2.033
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               39.597
Skew:                          -0.632   Prob(JB):                     2.52e-09
Kurtosis:                       3.349   Cond. No.                     2.22e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.22e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

C6 Results above. There are a number of differences. workprg, drugs, and educ flip signs. These lose their significance exept educ (which was not significant). Generally the remaining coefficients become smaller in absolute terms.

In [35]:
# Exercise 7
mroz = pd.read_stata("./stata/MROZ.DTA")
X = sm.add_constant(mroz[["educ", "exper", "expersq", "nwifeinc", "age", "kidslt6", "kidsge6"]])
model = sm.OLS(mroz.lwage, X, missing="drop").fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  lwage   R-squared:                       0.164
Model:                            OLS   Adj. R-squared:                  0.150
Method:                 Least Squares   F-statistic:                     11.78
Date:                Thu, 18 Aug 2022   Prob (F-statistic):           1.02e-13
Time:                        17:53:05   Log-Likelihood:                -429.74
No. Observations:                 428   AIC:                             875.5
Df Residuals:                     420   BIC:                             908.0
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.3580      0.318     -1.125      0.261      -0.984       0.268
educ           0.0999      0.015      6.616      0.000       0.070       0.130
exper          0.0407      0.013      3.044      0.002       0.014       0.067
expersq       -0.0007      0.000     -1.860      0.064      -0.002    4.24e-05
nwifeinc       0.0057      0.003      1.715      0.087      -0.001       0.012
age           -0.0035      0.005     -0.650      0.516      -0.014       0.007
kidslt6       -0.0559      0.089     -0.631      0.529      -0.230       0.118
kidsge6       -0.0176      0.028     -0.633      0.527      -0.072       0.037
==============================================================================
Omnibus:                       75.081   Durbin-Watson:                   1.966
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              297.845
Skew:                          -0.715   Prob(JB):                     2.11e-65
Kurtosis:                       6.828   Cond. No.                     3.56e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.56e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [36]:
import heckman as heckman
# heckman.py from https://github.com/statsmodels/statsmodels/blob/92ea62232fd63c7b60c60bee4517ab3711d906e3/statsmodels/regression/heckman.py
model = heckman.Heckman(mroz.lwage, X, X).fit(method='twostep')
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
       Heckman Regression Results      
=======================================
Dep. Variable:                    lwage
Model:                          Heckman
Method:                Heckman Two-Step
Date:                  Thu, 18 Aug 2022
Time:                          17:53:06
No. Total Obs.:                     753
No. Censored Obs.:                  325
No. Uncensored Obs.:                428
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.5603      0.459     -1.221      0.222      -1.459       0.339
educ           0.1187      0.034      3.486      0.000       0.052       0.185
exper          0.0598      0.034      1.777      0.076      -0.006       0.126
expersq       -0.0011      0.001     -1.649      0.099      -0.002       0.000
nwifeinc       0.0038      0.004      0.856      0.392      -0.005       0.013
age           -0.0112      0.013     -0.828      0.408      -0.038       0.015
kidslt6       -0.1880      0.231     -0.815      0.415      -0.640       0.264
kidsge6       -0.0122      0.030     -0.413      0.680      -0.070       0.046
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.2701      0.509      0.531      0.595      -0.727       1.267
educ           0.1309      0.025      5.183      0.000       0.081       0.180
exper          0.1233      0.019      6.590      0.000       0.087       0.160
expersq       -0.0019      0.001     -3.145      0.002      -0.003      -0.001
nwifeinc      -0.0120      0.005     -2.484      0.013      -0.022      -0.003
age           -0.0529      0.008     -6.235      0.000      -0.069      -0.036
kidslt6       -0.8683      0.119     -7.326      0.000      -1.101      -0.636
kidsge6        0.0360      0.043      0.828      0.408      -0.049       0.121
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
IMR (Lambda)     0.2885      0.464      0.622      0.534      -0.620       1.197
=====================================
rho:                            0.418
sigma:                          0.690
=====================================

First table are the estimates for the regression (response) equation.
Second table are the estimates for the selection equation.
Third table is the estimate for the coef of the inverse Mills ratio (Heckman's Lambda).
"""

In [37]:
lam = model.select_res.predict()
model = sm.OLS(lam, X, missing="drop").fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.977
Model:                            OLS   Adj. R-squared:                  0.976
Method:                 Least Squares   F-statistic:                     4429.
Date:                Thu, 18 Aug 2022   Prob (F-statistic):               0.00
Time:                        17:53:06   Log-Likelihood:                 1363.8
No. Observations:                 753   AIC:                            -2712.
Df Residuals:                     745   BIC:                            -2675.
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.5915      0.014     41.208      0.000       0.563       0.620
educ           0.0379      0.001     55.191      0.000       0.037       0.039
exper          0.0396      0.001     74.935      0.000       0.039       0.041
expersq       -0.0006   1.72e-05    -34.715      0.000      -0.001      -0.001
nwifeinc      -0.0032      0.000    -23.928      0.000      -0.003      -0.003
age           -0.0162      0.000    -70.215      0.000      -0.017      -0.016
kidslt6       -0.2645      0.003    -84.800      0.000      -0.271      -0.258
kidsge6        0.0128      0.001     10.433      0.000       0.010       0.015
==============================================================================
Omnibus:                      397.856   Durbin-Watson:                   1.910
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7522.401
Skew:                           1.939   Prob(JB):                         0.00
Kurtosis:                      17.991   Cond. No.                     3.06e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.06e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

C7.i Results above. educ is 0.0999 (se is 0.015)

C7.ii The Heckit results on educ is 0.1187 (se 0.034). Returns on education increase, but so does the standard error.

C7.iii The R-squared is very large (0.977), especially compared to the OLS. As suggested by the book, there is multicollinearity in the second stage, explaining the large errors.

In [38]:
# Exercise 8
jtrain2 = pd.read_stata("./stata/JTRAIN2.DTA")
jtrain2.train.sum()

185

In [39]:
jtrain2.mostrn.describe()

count    445.000000
mean       7.687640
std        9.656205
min        0.000000
25%        0.000000
50%        0.000000
75%       15.000000
max       24.000000
Name: mostrn, dtype: float64

In [40]:
X = sm.add_constant(jtrain2[["unem74", "unem75", "age", "educ", "black", "hisp", "married"]])
model = sm.OLS(jtrain2.train, X, missing="drop").fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  train   R-squared:                       0.022
Model:                            OLS   Adj. R-squared:                  0.007
Method:                 Least Squares   F-statistic:                     1.429
Date:                Thu, 18 Aug 2022   Prob (F-statistic):              0.192
Time:                        17:53:06   Log-Likelihood:                -311.53
No. Observations:                 445   AIC:                             639.1
Df Residuals:                     437   BIC:                             671.8
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.3380      0.189      1.784      0.075      -0.034       0.710
unem74         0.0209      0.077      0.270      0.787      -0.131       0.173
unem75        -0.0956      0.072     -1.329      0.184      -0.237       0.046
age            0.0032      0.003      0.942      0.347      -0.003       0.010
educ           0.0120      0.013      0.900      0.368      -0.014       0.038
black         -0.0817      0.088     -0.931      0.352      -0.254       0.091
hisp          -0.2000      0.117     -1.710      0.088      -0.430       0.030
married        0.0373      0.064      0.579      0.563      -0.089       0.164
==============================================================================
Omnibus:                     2209.423   Durbin-Watson:                   0.035
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               68.291
Skew:                           0.327   Prob(JB):                     1.48e-15
Kurtosis:                       1.195   Cond. No.                         250.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [41]:
model = sm.Probit(jtrain2.train, X, missing="drop").fit()
model.summary()

Optimization terminated successfully.
         Current function value: 0.667436
         Iterations 5


<class 'statsmodels.iolib.summary.Summary'>
"""
                          Probit Regression Results                           
==============================================================================
Dep. Variable:                  train   No. Observations:                  445
Model:                         Probit   Df Residuals:                      437
Method:                           MLE   Df Model:                            7
Date:                Thu, 18 Aug 2022   Pseudo R-squ.:                 0.01685
Time:                        17:53:06   Log-Likelihood:                -297.01
converged:                       True   LL-Null:                       -302.10
Covariance Type:            nonrobust   LLR p-value:                    0.1785
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.4241      0.487     -0.871      0.384      -1.379       0.530
unem74         0.0530      0.199      0.266      0.790      -0.338       0.444
unem75        -0.2477      0.185     -1.339      0.181      -0.610       0.115
age            0.0083      0.009      0.948      0.343      -0.009       0.026
educ           0.0314      0.034      0.916      0.360      -0.036       0.099
black         -0.2069      0.225     -0.920      0.358      -0.648       0.234
hisp          -0.5398      0.309     -1.750      0.080      -1.144       0.065
married        0.0966      0.166      0.584      0.560      -0.228       0.421
==============================================================================
"""

In [42]:
X = sm.add_constant(jtrain2.train)
model = sm.OLS(jtrain2.unem78, X, missing="drop").fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 unem78   R-squared:                       0.014
Model:                            OLS   Adj. R-squared:                  0.012
Method:                 Least Squares   F-statistic:                     6.265
Date:                Thu, 18 Aug 2022   Prob (F-statistic):             0.0127
Time:                        17:53:06   Log-Likelihood:                -284.30
No. Observations:                 445   AIC:                             572.6
Df Residuals:                     443   BIC:                             580.8
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.3538      0.028     12.419      0.000       0.298       0.410
train         -0.1106      0.044     -2.503      0.013      -0.197      -0.024
==============================================================================
Omnibus:                      529.053   Durbin-Watson:                   2.008
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               79.145
Skew:                           0.813   Prob(JB):                     6.51e-18
Kurtosis:                       1.727   Cond. No.                         2.47
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [43]:
model.predict()

array([0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324

In [44]:
model = sm.Probit(jtrain2.unem78, X, missing="drop").fit()
model.summary()

Optimization terminated successfully.
         Current function value: 0.610298
         Iterations 5


<class 'statsmodels.iolib.summary.Summary'>
"""
                          Probit Regression Results                           
==============================================================================
Dep. Variable:                 unem78   No. Observations:                  445
Model:                         Probit   Df Residuals:                      443
Method:                           MLE   Df Model:                            1
Date:                Thu, 18 Aug 2022   Pseudo R-squ.:                 0.01147
Time:                        17:53:07   Log-Likelihood:                -271.58
converged:                       True   LL-Null:                       -274.73
Covariance Type:            nonrobust   LLR p-value:                   0.01204
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.3750      0.080     -4.702      0.000      -0.531      -0.219
train         -0.3210      0.128     -2.498      0.012      -0.573      -0.069
==============================================================================
"""

In [45]:
model.predict()

array([0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324324,
       0.24324324, 0.24324324, 0.24324324, 0.24324324, 0.24324

In [46]:
X = sm.add_constant(jtrain2[["unem74", "unem75", "age", "educ", "black", "hisp", "married", "train"]])
model = sm.OLS(jtrain2.unem78, X, missing="drop").fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 unem78   R-squared:                       0.046
Model:                            OLS   Adj. R-squared:                  0.029
Method:                 Least Squares   F-statistic:                     2.640
Date:                Thu, 18 Aug 2022   Prob (F-statistic):            0.00780
Time:                        17:53:07   Log-Likelihood:                -276.90
No. Observations:                 445   AIC:                             571.8
Df Residuals:                     436   BIC:                             608.7
Df Model:                           8                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.1632      0.176      0.927      0.355      -0.183       0.509
unem74         0.0387      0.072      0.540      0.589      -0.102       0.179
unem75         0.0160      0.067      0.239      0.811      -0.115       0.147
age         4.332e-05      0.003      0.014      0.989      -0.006       0.006
educ           0.0001      0.012      0.012      0.991      -0.024       0.024
black          0.1888      0.081      2.322      0.021       0.029       0.349
hisp          -0.0377      0.109     -0.347      0.729      -0.251       0.176
married       -0.0254      0.060     -0.426      0.670      -0.143       0.092
train         -0.1117      0.044     -2.521      0.012      -0.199      -0.025
==============================================================================
Omnibus:                      440.373   Durbin-Watson:                   2.004
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               70.714
Skew:                           0.749   Prob(JB):                     4.41e-16
Kurtosis:                       1.748   Cond. No.                         251.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [47]:
ols_yhat = model.predict()
ols_yhat

array([ 0.27271826,  0.07068344,  0.29799657,  0.29772238,  0.29754956,
        0.2972173 ,  0.29769335,  0.29793897,  0.298227  ,  0.08385643,
        0.29708735,  0.29775095,  0.29689979,  0.27214084,  0.29671223,
        0.29723159,  0.29801086,  0.29740486,  0.29842975,  0.2978233 ,
        0.29754911,  0.10992876,  0.10907759,  0.29759242,  0.29718827,
        0.27237172,  0.29763574,  0.07104427,  0.29714496,  0.29759242,
        0.29714496,  0.29762235,  0.27219844,  0.29756339,  0.29777998,
        0.29880487,  0.29677029,  0.27225605,  0.27267539,  0.29744818,
        0.29760671,  0.10825456,  0.29685647,  0.04492863,  0.29741915,
        0.27219844,  0.29685647,  0.29700071,  0.29677029,  0.29769335,
        0.29733297,  0.27245835,  0.29733252,  0.29777998,  0.27241503,
        0.29714496,  0.29786707,  0.27188183,  0.27336757,  0.10867299,
        0.29685647,  0.29737628,  0.29792468,  0.29772238,  0.29679931,
        0.29747721,  0.29772238,  0.10813934,  0.27219934,  0.29

In [48]:
model = sm.Probit(jtrain2.unem78, X, missing="drop").fit()
model.summary()

Optimization terminated successfully.
         Current function value: 0.591714
         Iterations 5


<class 'statsmodels.iolib.summary.Summary'>
"""
                          Probit Regression Results                           
==============================================================================
Dep. Variable:                 unem78   No. Observations:                  445
Model:                         Probit   Df Residuals:                      436
Method:                           MLE   Df Model:                            8
Date:                Thu, 18 Aug 2022   Pseudo R-squ.:                 0.04158
Time:                        17:53:07   Log-Likelihood:                -263.31
converged:                       True   LL-Null:                       -274.73
Covariance Type:            nonrobust   LLR p-value:                  0.003570
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -1.0103      0.538     -1.878      0.060      -2.065       0.044
unem74         0.1061      0.213      0.499      0.618      -0.311       0.523
unem75         0.0636      0.197      0.323      0.747      -0.323       0.450
age            0.0007      0.009      0.074      0.941      -0.017       0.019
educ          -0.0019      0.037     -0.051      0.959      -0.074       0.070
black          0.6337      0.274      2.310      0.021       0.096       1.171
hisp          -0.1649      0.379     -0.435      0.663      -0.908       0.578
married       -0.0778      0.177     -0.439      0.661      -0.425       0.269
train         -0.3366      0.132     -2.557      0.011      -0.595      -0.079
==============================================================================
"""

In [49]:
probit_yhat = model.predict()
probit_yhat

array([0.26857824, 0.08942353, 0.29254246, 0.29249584, 0.29584837,
       0.29263486, 0.2909188 , 0.29365809, 0.28809977, 0.10467007,
       0.29193838, 0.28980804, 0.29235601, 0.26697604, 0.29277391,
       0.29128921, 0.29119701, 0.29221705, 0.29486926, 0.29161414,
       0.29156759, 0.1197992 , 0.12129037, 0.29179952, 0.29105746,
       0.2667985 , 0.29203154, 0.08966411, 0.2908258 , 0.29179952,
       0.2908258 , 0.30199318, 0.26591087, 0.29022423, 0.29138227,
       0.29403097, 0.29594125, 0.26484786, 0.27246916, 0.29244923,
       0.29045567, 0.11872202, 0.29212387, 0.07738361, 0.2908723 ,
       0.26591087, 0.29212387, 0.2914745 , 0.29594125, 0.2909188 ,
       0.29468212, 0.26724288, 0.2904092 , 0.29138227, 0.26702064,
       0.2908258 , 0.29612875, 0.27386183, 0.26782161, 0.11837376,
       0.29212387, 0.2949152 , 0.2950088 , 0.29249584, 0.29753079,
       0.29403012, 0.29249584, 0.12001467, 0.27413208, 0.29166069,
       0.29379736, 0.2956158 , 0.29365724, 0.29138227, 0.29013

In [50]:
np.corrcoef(ols_yhat, probit_yhat)

array([[1.      , 0.993244],
       [0.993244, 1.      ]])

In [51]:
X["train"] = 1
train_yhat = model.predict(X)
X["train"] = 0
notrain_yhat = model.predict(X)
(train_yhat - notrain_yhat).mean()

-0.11233068990929132

C8.i 185 men in the sample participated in the program. The longest period of training was 24 months.

C8.ii Results above. The F-statistic is reported in the summary and shows that the variables are not jointly significant.

C8.iii Results above. The p-value is 0.1785 and so, again, the variables are not jointly significant.

C8.iv There is no indication that any of these variables affect training and so train can be considered exogenous. Given that train was randomly assigned, this should not be a surprise.

C8.v Results above. In equation form $\hat{unem78} = .354 - .111 train$. Train appears to be significant (the negative coefficient makes sense since it should reduce unemployment).

C8.vi Results above. The coefficients cannot be meaningfully compared.

C8.vii The results are the same. Both variables are binary. The OLS version is a little easier to unpack but once the transformation for Probit is done, the results should be identical, since it's just measuring the 'switch' of train from 0 to 1 or otherwise. There is no practical difference between choosing one or the other in this case.

C8.viii Results above. The fitted probabilities are no longer identical. The correlation is still very high at 0.9932.

C8.ix The APE is -0.1123, while the coefficient for train when estimated by OLS is -0.1117. The results are close (-0.0006), but not identical. For practical purposes they should be considered close enough to be the same, meaning that the linear probability model and probit lead to the same conclusion as to the effect of training.

In [52]:
# Exercise 9
apple = pd.read_stata("./stata/APPLE.DTA")
apple[apple.ecolbs == 0].shape[0]

248

In [53]:
apple.ecolbs.describe()

count    660.00000
mean       1.47399
std        2.52578
min        0.00000
25%        0.00000
50%        1.00000
75%        2.00000
max       42.00000
Name: ecolbs, dtype: float64

In [54]:
X = sm.add_constant(apple[["ecoprc", "regprc", "faminc", "hhsize"]])
cens = np.zeros(apple.shape[0])
cens[apple.ecolbs == 0] = -1
model = Tobit(apple.ecolbs, X, cens=cens, missing="drop").fit()
model.summary()

Optimization terminated successfully.
         Current function value: 1.918852
         Iterations: 433
         Function evaluations: 681


<class 'statsmodels.iolib.summary.Summary'>
"""
                              Tobit Regression Results                             
===================================================================================
Dep. Variable:                      ecolbs   Pseudo R-squ:                    0.019
Method:                 Maximum Likelihood   Log-Likelihood:                -1266.4
No. Observations:                      660   LL-Null:                       -1291.1
No. Uncensored Obs:                    412   LL-Ratio:                         49.3
No. Left-censored Obs:                 248   LLR p-value:                     0.000
No. Right-censored Obs:                  0   AIC:                            2542.9
Df Residuals:                          655   BIC:                            2565.3
Df Model:                                4   Covariance Type:             nonrobust
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.0027      0.668      1.501      0.133      -0.307       2.312
ecoprc        -5.8214      0.886     -6.572      0.000      -7.558      -4.085
regprc         5.6550      1.065      5.312      0.000       3.568       7.742
faminc         0.0066      0.004      1.659      0.097      -0.001       0.014
hhsize         0.1303      0.095      1.371      0.170      -0.056       0.317
Log(Sigma)     1.2358      0.037     33.582      0.000       1.164       1.308
==============================================================================
"""

In [55]:
model.f_test("faminc = hhsize = 0")

<class 'statsmodels.stats.contrast.ContrastResults'>
<F test: F=2.568844095502758, p=0.07739588057855948, df_denom=655, df_num=2>

In [56]:
model.f_test("-ecoprc = regprc")

<class 'statsmodels.stats.contrast.ContrastResults'>
<F test: F=0.07907656849328355, p=0.7786415470274166, df_denom=655, df_num=1>

In [57]:
model = sm.OLS(apple.ecolbs, X, missing="drop").fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 ecolbs   R-squared:                       0.039
Model:                            OLS   Adj. R-squared:                  0.033
Method:                 Least Squares   F-statistic:                     6.707
Date:                Thu, 18 Aug 2022   Prob (F-statistic):           2.71e-05
Time:                        17:53:08   Log-Likelihood:                -1534.3
No. Observations:                 660   AIC:                             3079.
Df Residuals:                     655   BIC:                             3101.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.6295      0.450      3.618      0.000       0.745       2.514
ecoprc        -2.9030      0.588     -4.935      0.000      -4.058      -1.748
regprc         3.0306      0.711      4.263      0.000       1.635       4.426
faminc         0.0028      0.003      1.037      0.300      -0.003       0.008
hhsize         0.0537      0.064      0.841      0.401      -0.072       0.179
==============================================================================
Omnibus:                      993.848   Durbin-Watson:                   2.017
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           360854.165
Skew:                           8.351   Prob(JB):                         0.00
Kurtosis:                     116.327   Cond. No.                         588.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

C9.i 248 of the families would not buy any eco-friendly apples at the set price.

C9.ii While ecolbs is distributed over positive values, there may be some debate over whether or not it is continuous. 75% of all observations are at or below 2 pounds and there do not appear to be fractional values. Given that the variable is not continuous the assumption of normality is not likely to hold.

C9.iii ecoprc and regprc are significant at the 1% level.

C9.iv faminc and hhsize are only jointly significant at the 1% level.

C9.v An increase in the price of eco apples is associated with a decrease in purchases, in line with economic theory. Furthermore, an increase in the price of regular apples is associated with an increase in the purcase of eco apples as consumers substitute.

C9.vi We do not reject the null hypothesis that the absolute value of the two price coefficients are equal (p-value 0.7786).

C9.vii Predict is not implemented for the library. This will need to be revisited.

C9.viii Return once statsmodels has a Tobit function.

C9.ix Results for OLS above. The coefficients for OLS and Tobit should not be directly compared, since Tobit will involve some scaling. The R-Squared for the linear model appears to be better (though there is a question as to whether or not the estimate computed by the library is appropriate).

C9.x Goodness of fit does not determine consistency. Consistent estimators can still be a poor fit.

In [58]:
# Exercise 10
smoke = pd.read_stata("./stata/SMOKE.DTA")
print("Number of non-smokers:", smoke[smoke.cigs == 0].shape[0])
print("Fraction of people who claim to smoke 20:", smoke[smoke.cigs == 20].shape[0] / smoke.shape[0])
smoke.describe()

Number of non-smokers: 497
Fraction of people who claim to smoke 20: 0.1251548946716233


educ     cigpric       white         age        income  \
count  807.000000  807.000000  807.000000  807.000000    807.000000   
mean    12.470880   60.300365    0.878563   41.237918  19304.832714   
std      3.057161    4.738471    0.326837   17.027285   9142.958290   
min      6.000000   44.004002    0.000000   17.000000    500.000000   
25%     10.000000   58.141499    1.000000   28.000000  12500.000000   
50%     12.000000   61.053001    1.000000   38.000000  20000.000000   
75%     13.500000   63.179001    1.000000   54.000000  30000.000000   
max     18.000000   70.128998    1.000000   88.000000  30000.000000   

             cigs    restaurn     lincome        agesq    lcigpric  
count  807.000000  807.000000  807.000000   807.000000  807.000000  
mean     8.686493    0.246592    9.687323  1990.135068    4.096032  
std     13.721516    0.431295    0.712695  1577.165644    0.082919  
min      0.000000    0.000000    6.214608   289.000000    3.784281  
25%      0.000000    0.000000    9.433484   784.000000    4.062880  
50%      0.000000    0.000000    9.903487  1444.000000    4.111742  
75%     20.000000    0.000000   10.308952  2916.000000    4.145972  
max     80.000000    1.000000   10.308952  7744.000000    4.250336

In [59]:
X = sm.add_constant(smoke[["lcigpric", "lincome", "white", "educ", "age", "agesq"]])
model = sm.Poisson(smoke.cigs, X, missing="drop").fit()
model.summary()

Optimization terminated successfully.
         Current function value: 10.141302
         Iterations 12


<class 'statsmodels.iolib.summary.Summary'>
"""
                          Poisson Regression Results                          
==============================================================================
Dep. Variable:                   cigs   No. Observations:                  807
Model:                        Poisson   Df Residuals:                      800
Method:                           MLE   Df Model:                            6
Date:                Thu, 18 Aug 2022   Pseudo R-squ.:                 0.05342
Time:                        17:53:09   Log-Likelihood:                -8184.0
converged:                       True   LL-Null:                       -8645.9
Covariance Type:            nonrobust   LLR p-value:                2.853e-196
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.4628      0.615      2.380      0.017       0.258       2.667
lcigpric      -0.3553      0.144     -2.468      0.014      -0.637      -0.073
lincome        0.0846      0.020      4.209      0.000       0.045       0.124
white         -0.0019      0.037     -0.051      0.959      -0.075       0.071
educ          -0.0601      0.004    -14.209      0.000      -0.068      -0.052
age            0.1152      0.005     23.220      0.000       0.105       0.125
agesq         -0.0014   5.69e-05    -24.247      0.000      -0.001      -0.001
==============================================================================
"""

In [60]:
sigma_sq = (((model.resid**2) / model.predict()).sum() / model.df_resid)
sigma_sq

20.60604898233917

In [61]:
sigma = np.sqrt(sigma_sq)
sigma

4.53938861327593

In [62]:
model.bse * sigma

const       2.789542
lcigpric    0.653397
lincome     0.091272
white       0.168833
educ        0.019200
age         0.022522
agesq       0.000258
dtype: float64

In [63]:
model.tvalues / sigma

const       0.524402
lcigpric   -0.543701
lincome     0.927256
white      -0.011254
educ       -3.130067
age         5.115237
agesq      -5.341390
dtype: float64

In [64]:
abs(model.tvalues / sigma) > 1.96

const       False
lcigpric    False
lincome     False
white       False
educ         True
age          True
agesq        True
dtype: bool

In [65]:
pd.Series(model.predict()).describe()

count    807.000000
mean       8.686493
std        3.059493
min        0.515012
25%        6.508632
50%        8.595273
75%       10.805913
max       18.835668
dtype: float64

In [66]:
np.corrcoef(smoke.cigs, model.predict())[0, 1] ** 2

0.0432056497070641

In [67]:
model = sm.OLS(smoke.cigs, X, missing="drop").fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                   cigs   R-squared:                       0.045
Model:                            OLS   Adj. R-squared:                  0.038
Method:                 Least Squares   F-statistic:                     6.300
Date:                Thu, 18 Aug 2022   Prob (F-statistic):           1.74e-06
Time:                        17:53:09   Log-Likelihood:                -3239.5
No. Observations:                 807   AIC:                             6493.
Df Residuals:                     800   BIC:                             6526.
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.7669     24.079      0.239      0.811     -41.499      53.033
lcigpric      -2.9009      5.747     -0.505      0.614     -14.181       8.380
lincome        0.7535      0.730      1.032      0.302      -0.679       2.186
white         -0.2049      1.458     -0.141      0.888      -3.067       2.657
educ          -0.5143      0.168     -3.067      0.002      -0.843      -0.185
age            0.7821      0.161      4.856      0.000       0.466       1.098
agesq         -0.0091      0.002     -5.201      0.000      -0.013      -0.006
==============================================================================
Omnibus:                      230.498   Durbin-Watson:                   1.997
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              514.407
Skew:                           1.562   Prob(JB):                    1.99e-112
Kurtosis:                       5.353   Cond. No.                     1.32e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

C10.i 497 people are nonsmokers. About 12.5% of the sample claims to smoke 20 cigarettes a day. This seems unusual for a continuous variable, but could be explained by how many cigarettes are in a pack?

C10.ii There would be a concern for the pileups since Poisson is smoother, but it does not seem to be a dealbreaker given the discussion of robustness in the text.

C10.iii Results above. The estimated price elasticity for cigarettes is -0.3553, while the income elasticity is 0.0846.

C10.iv Both the price an dincome variables are statistically significant at the 5% level.

C10.v $\hat{\sigma}^2 = 20.6060$ and $\hat{\sigma} = 4.5394$ which indicates overdispersion. The standard errors should be multiplied by about 4.54.

C10.vi The question recommmends adjusted standard errors (reported above), but it is slightly easier to use t-statistics (absolute value greater than 1.96). Only education, age and age squared are the only variables that remain significant. There is no evidence that the coefficients for income or price are significantly different than zero.

C10.vii Answer is slightly anticipated in (vi) and both are significant. The education variable can be interpreted as saying that each year of education decreases the expected number of cigarettes smoked by about 6%.

C10.viii The minimum value is 0.5150 and the maximum is 18.8357. One trouble with the predicted values is that it estimates some level of smoking for everyone in the sample, when in reality there are a considerable number of non-smokers (more than half). The maximum in the sample vs. the prediction is also quite small (4 packs vs. not even a full pack), meaning it does not do a good job of predicting heavy smoking.

C10.ix The squared correlation coefficient is 0.0432

C10.x Results from OLS above. The R-squared is (very) slightly higher. It would be difficult to argue one provides a better fit than the other and both R-squareds are small.

In [68]:
# Exercise 11
cps91 = pd.read_stata("./stata/cps91.dta")
cps91[cps91.inlf > 0].shape[0] / cps91.shape[0]

0.5832445864394746

In [69]:
X = sm.add_constant(cps91[["educ", "exper", "expersq", "black", "hispanic"]])
model = sm.OLS(cps91.lwage, X, missing="drop").fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  lwage   R-squared:                       0.205
Model:                            OLS   Adj. R-squared:                  0.204
Method:                 Least Squares   F-statistic:                     169.1
Date:                Thu, 18 Aug 2022   Prob (F-statistic):          2.16e-160
Time:                        17:53:10   Log-Likelihood:                -2168.3
No. Observations:                3286   AIC:                             4349.
Df Residuals:                    3280   BIC:                             4385.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.6488      0.060     10.820      0.000       0.531       0.766
educ           0.0992      0.004     27.620      0.000       0.092       0.106
exper          0.0199      0.003      6.043      0.000       0.013       0.026
expersq       -0.0003    7.7e-05     -4.530      0.000      -0.000      -0.000
black         -0.0296      0.034     -0.861      0.390      -0.097       0.038
hispanic       0.0136      0.036      0.375      0.708      -0.058       0.085
==============================================================================
Omnibus:                      582.580   Durbin-Watson:                   1.965
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             8054.007
Skew:                          -0.415   Prob(JB):                         0.00
Kurtosis:                      10.625   Cond. No.                     4.71e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.71e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [70]:
model.f_test("black = hispanic = 0")

<class 'statsmodels.stats.contrast.ContrastResults'>
<F test: F=0.4582618927600699, p=0.6324223206732954, df_denom=3.28e+03, df_num=2>

In [71]:
X = sm.add_constant(cps91[["educ", "exper", "expersq", "black", "hispanic", "nwifeinc", "kidlt6"]])
model = sm.Probit(cps91.inlf, X, missing="drop").fit()
model.summary()

Optimization terminated successfully.
         Current function value: 0.627841
         Iterations 5


<class 'statsmodels.iolib.summary.Summary'>
"""
                          Probit Regression Results                           
==============================================================================
Dep. Variable:                   inlf   No. Observations:                 5634
Model:                         Probit   Df Residuals:                     5626
Method:                           MLE   Df Model:                            7
Date:                Thu, 18 Aug 2022   Pseudo R-squ.:                 0.07565
Time:                        17:53:10   Log-Likelihood:                -3537.3
converged:                       True   LL-Null:                       -3826.7
Covariance Type:            nonrobust   LLR p-value:                8.184e-121
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.4393      0.134     -3.282      0.001      -0.702      -0.177
educ           0.0965      0.008     12.393      0.000       0.081       0.112
exper          0.0077      0.007      1.066      0.287      -0.006       0.022
expersq       -0.0006      0.000     -3.895      0.000      -0.001      -0.000
black          0.0168      0.076      0.222      0.825      -0.131       0.165
hispanic      -0.1220      0.070     -1.731      0.084      -0.260       0.016
nwifeinc      -0.0091      0.001    -13.467      0.000      -0.010      -0.008
kidlt6        -0.5002      0.045    -11.047      0.000      -0.589      -0.411
==============================================================================
"""

In [72]:
cps91["lambda_hat"] = stats.norm.pdf(model.fittedvalues) / stats.norm.cdf(model.fittedvalues)
X = sm.add_constant(cps91[["educ", "exper", "expersq", "black", "hispanic", "lambda_hat"]])
model = sm.OLS(cps91.lwage, X, missing="drop").fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  lwage   R-squared:                       0.206
Model:                            OLS   Adj. R-squared:                  0.204
Method:                 Least Squares   F-statistic:                     141.5
Date:                Thu, 18 Aug 2022   Prob (F-statistic):          6.21e-160
Time:                        17:53:10   Log-Likelihood:                -2166.7
No. Observations:                3286   AIC:                             4347.
Df Residuals:                    3279   BIC:                             4390.
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.5389      0.086      6.240      0.000       0.370       0.708
educ           0.1033      0.004     24.127      0.000       0.095       0.112
exper          0.0205      0.003      6.199      0.000       0.014       0.027
expersq       -0.0004   7.87e-05     -4.802      0.000      -0.001      -0.000
black         -0.0251      0.034     -0.731      0.465      -0.093       0.042
hispanic       0.0057      0.037      0.154      0.877      -0.066       0.077
lambda_hat     0.0919      0.052      1.769      0.077      -0.010       0.194
==============================================================================
Omnibus:                      587.495   Durbin-Watson:                   1.968
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             8202.092
Skew:                          -0.420   Prob(JB):                         0.00
Kurtosis:                      10.694   Cond. No.                     7.40e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.4e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

C11.i About 58.32% of the women are in the workforce (indicated by positive earnings)

C11.ii Results above. The p-values are large including for a test of joint significance and so we cannot say there is a significant wage difference by ethnicity from OLS.

C11.iii Both variables are statistically significant. kidlt6 has a negative coefficient since we would normally expect these to be negatively associated with labour force participation. Spousal income is also likely to be negatively associated with labour force participation and so the negative coefficient is in line with expectations as well.

C11.iv kidl6 affects labour force participation and isn't likely to be connected with the wage offer. A similar argument might be made for nwifeinc although possibly this may indicate a social network for a particular kind of job?

C11.v The p-value for the inverse mills ratio is 0.077. There are thousands of observations so this does not seem particularly small.

C11.vi The signs and significance stay the same and generally the significant variables aren't too far away from OLS. black and hispanic have larger changes but still aren't significant.

In [73]:
# Exercise 12
charity = pd.read_stata("./stata/charity.dta")
charity.respond.sum()

1707

In [74]:
X = sm.add_constant(charity[["resplast", "weekslast", "propresp", "mailsyear", "avggift"]])
model = sm.Probit(charity.respond, X, missing="drop").fit()
model.summary()

Optimization terminated successfully.
         Current function value: 0.556752
         Iterations 7


<class 'statsmodels.iolib.summary.Summary'>
"""
                          Probit Regression Results                           
==============================================================================
Dep. Variable:                respond   No. Observations:                 4268
Model:                         Probit   Df Residuals:                     4262
Method:                           MLE   Df Model:                            5
Date:                Thu, 18 Aug 2022   Pseudo R-squ.:                  0.1727
Time:                        17:53:10   Log-Likelihood:                -2376.2
converged:                       True   LL-Null:                       -2872.3
Covariance Type:            nonrobust   LLR p-value:                2.893e-212
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -1.2949      0.114    -11.331      0.000      -1.519      -1.071
resplast       0.1261      0.057      2.204      0.028       0.014       0.238
weekslast     -0.0046      0.001     -6.413      0.000      -0.006      -0.003
propresp       1.8493      0.114     16.183      0.000       1.625       2.073
mailsyear      0.1462      0.032      4.577      0.000       0.084       0.209
avggift        0.0011      0.001      1.001      0.317      -0.001       0.003
==============================================================================
"""

In [75]:
model.get_margeff().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
       Probit Marginal Effects       
=====================================
Dep. Variable:                respond
Method:                          dydx
At:                           overall
==============================================================================
                dy/dx    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
resplast       0.0397      0.018      2.209      0.027       0.004       0.075
weekslast     -0.0014      0.000     -6.484      0.000      -0.002      -0.001
propresp       0.5822      0.033     17.869      0.000       0.518       0.646
mailsyear      0.0460      0.010      4.609      0.000       0.026       0.066
avggift        0.0004      0.000      1.002      0.317      -0.000       0.001
==============================================================================
"""

In [76]:
sm.OLS(charity.respond, X, missing="drop").fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                respond   R-squared:                       0.214
Model:                            OLS   Adj. R-squared:                  0.214
Method:                 Least Squares   F-statistic:                     232.7
Date:                Thu, 18 Aug 2022   Prob (F-statistic):          3.16e-220
Time:                        17:53:10   Log-Likelihood:                -2495.4
No. Observations:                4268   AIC:                             5003.
Df Residuals:                    4262   BIC:                             5041.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0165      0.036      0.464      0.643      -0.053       0.086
resplast       0.0665      0.019      3.495      0.000       0.029       0.104
weekslast     -0.0011      0.000     -5.168      0.000      -0.001      -0.001
propresp       0.6503      0.037     17.577      0.000       0.578       0.723
mailsyear      0.0520      0.010      5.099      0.000       0.032       0.072
avggift        0.0002   8.46e-05      2.160      0.031    1.69e-05       0.000
==============================================================================
Omnibus:                     1132.566   Durbin-Watson:                   1.960
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              240.879
Skew:                           0.280   Prob(JB):                     4.94e-53
Kurtosis:                       1.979   Cond. No.                         589.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [77]:
X = sm.add_constant(charity[["resplast", "weekslast", "propresp", "mailsyear", "avggift"]])
cens = np.zeros(charity.shape[0])
cens[charity.gift == 0 ] = -1
model = Tobit(charity.gift, X, cens=cens, missing="drop").fit()
model.summary()

Optimization terminated successfully.
         Current function value: 2.172543
         Iterations: 1187
         Function evaluations: 1777


<class 'statsmodels.iolib.summary.Summary'>
"""
                              Tobit Regression Results                             
===================================================================================
Dep. Variable:                        gift   Pseudo R-squ:                    0.041
Method:                 Maximum Likelihood   Log-Likelihood:                -9272.4
No. Observations:                     4268   LL-Null:                       -9670.7
No. Uncensored Obs:                   1707   LL-Ratio:                        796.6
No. Left-censored Obs:                2561   LLR p-value:                     0.000
No. Right-censored Obs:                  0   AIC:                           18556.8
Df Residuals:                         4262   BIC:                           18595.0
Df Model:                                5   Covariance Type:             nonrobust
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const        -28.5944      2.784    -10.271      0.000     -34.051     -23.138
resplast       1.6857      1.358      1.241      0.215      -0.977       4.348
weekslast     -0.1307      0.018     -7.361      0.000      -0.166      -0.096
propresp      35.1482      2.680     13.114      0.000      29.895      40.401
mailsyear      4.0041      0.754      5.310      0.000       2.526       5.482
avggift        0.0271      0.005      5.087      0.000       0.017       0.037
Log(Sigma)     3.2961      0.019    175.119      0.000       3.259       3.333
==============================================================================
"""

In [78]:
model.params / model.params[-1]

array([-8.67521493e+00,  5.11415552e-01, -3.96579189e-02,  1.06635645e+01,
        1.21481182e+00,  8.20751260e-03,  1.00000000e+00])

C12.i 1707 people responded to the most recent request

C12.ii All variables except avggift are significant at the 5% level (resplast, weekslast, propresp, mailsyear). All but resplast are significant at the 1% level.

C12.iii The APE for mailsyear 0.046, in contrast to the 0.0520 for the linear probability model.

C12.iv Everything but resplast is significant at the 1% level.

C12.v get_margeff() not implemented in this version of Tobit. Will be completed later.

C12.vi There isn't a change in signs and significance, but the specification issues section suggested the probit estimate should be close to the Tobit estimate divided by sigma and they do not appear to be.

In [79]:
# Exercise 12
htv = pd.read_stata("./stata/HTV.DTA")
X = sm.add_constant(htv[["educ", "abil", "exper", "nc", "west", "south", "urban"]])
model = sm.OLS(htv.lwage, X, missing="drop").fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  lwage   R-squared:                       0.234
Model:                            OLS   Adj. R-squared:                  0.229
Method:                 Least Squares   F-statistic:                     53.23
Date:                Thu, 18 Aug 2022   Prob (F-statistic):           1.77e-66
Time:                        17:53:15   Log-Likelihood:                -939.84
No. Observations:                1230   AIC:                             1896.
Df Residuals:                    1222   BIC:                             1937.
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.3987      0.185      2.158      0.031       0.036       0.761
educ           0.1037      0.010     10.704      0.000       0.085       0.123
abil           0.0558      0.008      6.565      0.000       0.039       0.072
exper          0.0448      0.007      6.619      0.000       0.032       0.058
nc            -0.1397      0.041     -3.440      0.001      -0.219      -0.060
west          -0.1282      0.049     -2.638      0.008      -0.224      -0.033
south         -0.1227      0.045     -2.742      0.006      -0.210      -0.035
urban          0.2268      0.041      5.589      0.000       0.147       0.306
==============================================================================
Omnibus:                       70.134   Durbin-Watson:                   1.903
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              145.589
Skew:                          -0.368   Prob(JB):                     2.43e-32
Kurtosis:                       4.516   Cond. No.                         214.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [80]:
htv_less16 = htv[htv.educ < 16]
print("Original sample:", htv.shape[0], "Restricted sample:", htv_less16.shape[0], "Observations dropped:", (1 - htv_less16.shape[0] / htv.shape[0]) * 100, "percent")
X = sm.add_constant(htv_less16[["educ", "abil", "exper", "nc", "west", "south", "urban"]])
model = sm.OLS(htv_less16.lwage, X, missing="drop").fit()
model.summary()

Original sample: 1230 Restricted sample: 1064 Observations dropped: 13.495934959349597 percent


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  lwage   R-squared:                       0.203
Model:                            OLS   Adj. R-squared:                  0.197
Method:                 Least Squares   F-statistic:                     38.33
Date:                Thu, 18 Aug 2022   Prob (F-statistic):           4.38e-48
Time:                        17:53:15   Log-Likelihood:                -811.02
No. Observations:                1064   AIC:                             1638.
Df Residuals:                    1056   BIC:                             1678.
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.2794      0.215      1.301      0.193      -0.142       0.701
educ           0.1182      0.013      9.375      0.000       0.093       0.143
abil           0.0489      0.009      5.478      0.000       0.031       0.066
exper          0.0412      0.007      5.682      0.000       0.027       0.055
nc            -0.1412      0.043     -3.246      0.001      -0.227      -0.056
west          -0.1361      0.053     -2.563      0.011      -0.240      -0.032
south         -0.1124      0.048     -2.326      0.020      -0.207      -0.018
urban          0.2199      0.042      5.219      0.000       0.137       0.303
==============================================================================
Omnibus:                       76.691   Durbin-Watson:                   1.933
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              152.960
Skew:                          -0.469   Prob(JB):                     6.10e-34
Kurtosis:                       4.603   Cond. No.                         230.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [81]:
htv_less20 = htv[htv.wage < 20]
X = sm.add_constant(htv_less20[["educ", "abil", "exper", "nc", "west", "south", "urban"]])
model = sm.OLS(htv_less20.lwage, X, missing="drop").fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  lwage   R-squared:                       0.183
Model:                            OLS   Adj. R-squared:                  0.178
Method:                 Least Squares   F-statistic:                     33.85
Date:                Thu, 18 Aug 2022   Prob (F-statistic):           1.07e-42
Time:                        17:53:16   Log-Likelihood:                -651.59
No. Observations:                1066   AIC:                             1319.
Df Residuals:                    1058   BIC:                             1359.
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.1795      0.174      6.795      0.000       0.839       1.520
educ           0.0579      0.009      6.258      0.000       0.040       0.076
abil           0.0548      0.008      7.168      0.000       0.040       0.070
exper          0.0218      0.006      3.467      0.001       0.009       0.034
nc            -0.1373      0.038     -3.644      0.000      -0.211      -0.063
west          -0.1415      0.045     -3.120      0.002      -0.230      -0.053
south         -0.1176      0.042     -2.833      0.005      -0.199      -0.036
urban          0.1653      0.037      4.525      0.000       0.094       0.237
==============================================================================
Omnibus:                      212.364   Durbin-Watson:                   1.917
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              445.438
Skew:                          -1.126   Prob(JB):                     1.88e-97
Kurtosis:                       5.227   Cond. No.                         216.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

C13.i Results above. The estimated return to education is about 0.1037 with a standard error of 0.010.

C13.ii About 13.5% of the sample is dropped. Returns to education increase to 0.1182 (which is still within the confidence interval of the full sample).

C13.iii Returns to education drop considerably, down to 0.0579 while still retaining significance.

C13.iv The implementation of censored regression I had was dubious. Will return to this question later.

In [82]:
# Exercise 14
happiness = pd.read_stata("./stata/happiness.dta")
X = sm.add_constant(happiness[["occattend", "regattend", "y94", "y98", "y00", "y02", "y04"]])
model = sm.OLS(happiness.vhappy, X, missing="drop").fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 vhappy   R-squared:                       0.007
Model:                            OLS   Adj. R-squared:                  0.007
Method:                 Least Squares   F-statistic:                     17.17
Date:                Thu, 18 Aug 2022   Prob (F-statistic):           8.47e-23
Time:                        17:53:16   Log-Likelihood:                -10816.
No. Observations:               16864   AIC:                         2.165e+04
Df Residuals:                   16856   BIC:                         2.171e+04
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.2909      0.007     43.236      0.000       0.278       0.304
occattend      0.0041      0.008      0.511      0.610      -0.012       0.020
regattend      0.1121      0.011     10.364      0.000       0.091       0.133
y94           -0.0195      0.010     -1.875      0.061      -0.040       0.001
y98            0.0083      0.011      0.782      0.434      -0.013       0.029
y00            0.0117      0.011      1.093      0.274      -0.009       0.033
y02           -0.0038      0.014     -0.274      0.784      -0.031       0.023
y04            0.0056      0.014      0.402      0.688      -0.022       0.033
==============================================================================
Omnibus:                    37876.985   Durbin-Watson:                   1.941
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3083.265
Skew:                           0.831   Prob(JB):                         0.00
Kurtosis:                       1.726   Cond. No.                         5.59
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [83]:
model = sm.Probit(happiness.vhappy, X, missing="drop").fit()
model.summary()

Optimization terminated successfully.
         Current function value: 0.613115
         Iterations 4


<class 'statsmodels.iolib.summary.Summary'>
"""
                          Probit Regression Results                           
==============================================================================
Dep. Variable:                 vhappy   No. Observations:                16864
Model:                         Probit   Df Residuals:                    16856
Method:                           MLE   Df Model:                            7
Date:                Thu, 18 Aug 2022   Pseudo R-squ.:                0.005527
Time:                        17:53:16   Log-Likelihood:                -10340.
converged:                       True   LL-Null:                       -10397.
Covariance Type:            nonrobust   LLR p-value:                 8.665e-22
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.5506      0.019    -28.493      0.000      -0.589      -0.513
occattend      0.0119      0.023      0.511      0.609      -0.034       0.058
regattend      0.3051      0.030     10.143      0.000       0.246       0.364
y94           -0.0563      0.030     -1.873      0.061      -0.115       0.003
y98            0.0235      0.030      0.775      0.438      -0.036       0.083
y00            0.0331      0.031      1.084      0.278      -0.027       0.093
y02           -0.0107      0.040     -0.270      0.787      -0.089       0.067
y04            0.0159      0.040      0.398      0.691      -0.062       0.094
==============================================================================
"""

In [84]:
model.get_margeff().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
       Probit Marginal Effects       
=====================================
Dep. Variable:                 vhappy
Method:                          dydx
At:                           overall
==============================================================================
                dy/dx    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
occattend      0.0042      0.008      0.511      0.609      -0.012       0.020
regattend      0.1065      0.010     10.234      0.000       0.086       0.127
y94           -0.0197      0.010     -1.874      0.061      -0.040       0.001
y98            0.0082      0.011      0.775      0.438      -0.013       0.029
y00            0.0116      0.011      1.084      0.278      -0.009       0.032
y02           -0.0037      0.014     -0.270      0.787      -0.031       0.023
y04            0.0055      0.014      0.398      0.691      -0.022       0.033
==============================================================================
"""

In [85]:
happiness["highinc"] = 0
happiness.loc[happiness.income == "$25000 or more", "highinc"] = 1
X = sm.add_constant(happiness[["occattend", "regattend", "highinc", "unem10", "educ", "teens", "y94", "y98", "y00", "y02", "y04"]])
model = sm.Probit(happiness.vhappy, X, missing="drop").fit()
model.summary()

Optimization terminated successfully.
         Current function value: 0.600941
         Iterations 5


<class 'statsmodels.iolib.summary.Summary'>
"""
                          Probit Regression Results                           
==============================================================================
Dep. Variable:                 vhappy   No. Observations:                11070
Model:                         Probit   Df Residuals:                    11058
Method:                           MLE   Df Model:                           11
Date:                Thu, 18 Aug 2022   Pseudo R-squ.:                 0.02300
Time:                        17:53:17   Log-Likelihood:                -6652.4
converged:                       True   LL-Null:                       -6809.0
Covariance Type:            nonrobust   LLR p-value:                 1.410e-60
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.8430      0.063    -13.373      0.000      -0.967      -0.719
occattend     -0.0222      0.029     -0.764      0.445      -0.079       0.035
regattend      0.2959      0.037      7.944      0.000       0.223       0.369
highinc        0.2091      0.027      7.678      0.000       0.156       0.262
unem10        -0.2793      0.028     -9.978      0.000      -0.334      -0.224
educ           0.0190      0.004      4.231      0.000       0.010       0.028
teens         -0.0453      0.026     -1.725      0.084      -0.097       0.006
y94           -0.0054      0.037     -0.144      0.885      -0.078       0.067
y98            0.0484      0.038      1.287      0.198      -0.025       0.122
y00            0.0723      0.038      1.883      0.060      -0.003       0.148
y02           -0.0649      0.050     -1.300      0.194      -0.163       0.033
y04           -0.0155      0.050     -0.309      0.757      -0.114       0.083
==============================================================================
"""

In [86]:
model.get_margeff().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
       Probit Marginal Effects       
=====================================
Dep. Variable:                 vhappy
Method:                          dydx
At:                           overall
==============================================================================
                dy/dx    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
occattend     -0.0076      0.010     -0.764      0.445      -0.027       0.012
regattend      0.1011      0.013      8.010      0.000       0.076       0.126
highinc        0.0714      0.009      7.734      0.000       0.053       0.090
unem10        -0.0954      0.009    -10.100      0.000      -0.114      -0.077
educ           0.0065      0.002      4.241      0.000       0.003       0.009
teens         -0.0155      0.009     -1.726      0.084      -0.033       0.002
y94           -0.0018      0.013     -0.144      0.885      -0.027       0.023
y98            0.0165      0.013      1.287      0.198      -0.009       0.042
y00            0.0247      0.013      1.883      0.060      -0.001       0.050
y02           -0.0222      0.017     -1.300      0.194      -0.056       0.011
y04           -0.0053      0.017     -0.309      0.757      -0.039       0.028
==============================================================================
"""

In [87]:
X = sm.add_constant(happiness[["occattend", "regattend", "highinc", "unem10", "educ", "teens", "black", "female", "blackfemale", "y94", "y98", "y00", "y02", "y04"]])
model = sm.Probit(happiness.vhappy, X, missing="drop").fit()
model.summary()

Optimization terminated successfully.
         Current function value: 0.600016
         Iterations 5


<class 'statsmodels.iolib.summary.Summary'>
"""
                          Probit Regression Results                           
==============================================================================
Dep. Variable:                 vhappy   No. Observations:                11070
Model:                         Probit   Df Residuals:                    11055
Method:                           MLE   Df Model:                           14
Date:                Thu, 18 Aug 2022   Pseudo R-squ.:                 0.02451
Time:                        17:53:17   Log-Likelihood:                -6642.2
converged:                       True   LL-Null:                       -6809.0
Covariance Type:            nonrobust   LLR p-value:                 1.059e-62
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
const          -0.8049      0.066    -12.236      0.000      -0.934      -0.676
occattend      -0.0123      0.029     -0.421      0.674      -0.070       0.045
regattend       0.3100      0.037      8.269      0.000       0.237       0.383
highinc         0.1945      0.028      7.051      0.000       0.140       0.249
unem10         -0.2749      0.028     -9.804      0.000      -0.330      -0.220
educ            0.0175      0.004      3.901      0.000       0.009       0.026
teens          -0.0387      0.026     -1.470      0.141      -0.090       0.013
black          -0.1205      0.063     -1.923      0.054      -0.243       0.002
female          0.0090      0.027      0.332      0.740      -0.044       0.062
blackfemale    -0.0828      0.079     -1.043      0.297      -0.238       0.073
y94            -0.0097      0.037     -0.262      0.793      -0.083       0.063
y98             0.0482      0.038      1.282      0.200      -0.025       0.122
y00             0.0725      0.038      1.887      0.059      -0.003       0.148
y02            -0.0634      0.050     -1.269      0.204      -0.161       0.035
y04            -0.0176      0.050     -0.350      0.726      -0.116       0.081
===============================================================================
"""

In [88]:
model.f_test("black=female=blackfemale=0")

<class 'statsmodels.stats.contrast.ContrastResults'>
<F test: F=6.722709639790956, p=0.00015796516398049632, df_denom=1.11e+04, df_num=3>

C14.i The direction and significance of the variables is the same (regattend is significant, occattend isn't). The dummies are not significant.

C14.ii regattend continues to be significant and goes from 0.1065 to 0.1011. It has fallen and significance has dropped, but not substantially.

C14.iii highinc, and educ are positive and significant. We would associate income and education with happiness so these make sense. Unemployment is negative and significant, again we'd expect unemployment to be a drag on happiness. The one curious result is the negative coefficient on teens (no strong prior as to whether it should be positive or negative), however, it is not statistically significant and so we cannot say it's any different than 0.

C14.iv Adding black, female and the interaction between the two shows no single variable is significant (black is close with a p-value of 0.054). However, a test of joint significance is significant suggesting that there are differences in happiness by gender or race.

In [89]:
# Exercise 15
alcohol = pd.read_stata("./stata/alcohol.dta")
print((alcohol.employ.sum() / alcohol.shape[0]) * 100, "percent of the sample is employed.")
print((alcohol.abuse.sum() / alcohol.shape[0]) * 100, "percent of the sample has abused alcohol.")

89.81877418041132 percent of the sample is employed.
9.916513948279373 percent of the sample has abused alcohol.


In [90]:
X = sm.add_constant(alcohol[["abuse"]])
model = sm.OLS(alcohol.employ, X, missing="drop").fit(cov_type="HC3")
alcohol["LPM_yhat"] = model.predict()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 employ   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                  0.001
Method:                 Least Squares   F-statistic:                     6.441
Date:                Thu, 18 Aug 2022   Prob (F-statistic):             0.0112
Time:                        17:53:17   Log-Likelihood:                -2185.9
No. Observations:                9822   AIC:                             4376.
Df Residuals:                    9820   BIC:                             4390.
Df Model:                           1                                         
Covariance Type:                  HC3                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.9010      0.003    283.730      0.000       0.895       0.907
abuse         -0.0283      0.011     -2.538      0.011      -0.050      -0.006
==============================================================================
Omnibus:                     4964.208   Durbin-Watson:                   1.963
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            21268.339
Skew:                          -2.631   Prob(JB):                         0.00
Kurtosis:                       7.929   Cond. No.                         3.38
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
"""

In [91]:
model = sm.Probit(alcohol.employ, X, missing="drop").fit()
alcohol["probit_yhat"] = model.predict()
model.summary()

Optimization terminated successfully.
         Current function value: 0.328678
         Iterations 6


<class 'statsmodels.iolib.summary.Summary'>
"""
                          Probit Regression Results                           
==============================================================================
Dep. Variable:                 employ   No. Observations:                 9822
Model:                         Probit   Df Residuals:                     9820
Method:                           MLE   Df Model:                            1
Date:                Thu, 18 Aug 2022   Pseudo R-squ.:                0.001120
Time:                        17:53:18   Log-Likelihood:                -3228.3
converged:                       True   LL-Null:                       -3231.9
Covariance Type:            nonrobust   LLR p-value:                  0.007140
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.2872      0.018     70.630      0.000       1.252       1.323
abuse         -0.1480      0.054     -2.723      0.006      -0.255      -0.041
==============================================================================
"""

In [92]:
model.get_margeff().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
       Probit Marginal Effects       
=====================================
Dep. Variable:                 employ
Method:                          dydx
At:                           overall
==============================================================================
                dy/dx    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
abuse         -0.0263      0.010     -2.722      0.006      -0.045      -0.007
==============================================================================
"""

In [93]:
alcohol.loc[alcohol.abuse == 0, ["LPM_yhat", "probit_yhat"]]

LPM_yhat  probit_yhat
1     0.900995     0.900995
2     0.900995     0.900995
3     0.900995     0.900995
4     0.900995     0.900995
5     0.900995     0.900995
...        ...          ...
9817  0.900995     0.900995
9818  0.900995     0.900995
9819  0.900995     0.900995
9820  0.900995     0.900995
9821  0.900995     0.900995

[8848 rows x 2 columns]

In [94]:
alcohol.loc[alcohol.abuse == 1, ["LPM_yhat", "probit_yhat"]]

LPM_yhat  probit_yhat
0      0.87269      0.87269
11     0.87269      0.87269
35     0.87269      0.87269
36     0.87269      0.87269
37     0.87269      0.87269
...        ...          ...
9773   0.87269      0.87269
9778   0.87269      0.87269
9789   0.87269      0.87269
9791   0.87269      0.87269
9814   0.87269      0.87269

[974 rows x 2 columns]

In [95]:
X = sm.add_constant(alcohol[["abuse", "age", "agesq", "educ", "educsq", "married", "famsize", "white", "northeast", "midwest", "south", "centcity", "outercity", "qrt1", "qrt2", "qrt3"]])
model = sm.OLS(alcohol.employ, X, missing="drop").fit(cov_type="HC3")
alcohol["LPM_yhat"] = model.predict()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 employ   R-squared:                       0.069
Model:                            OLS   Adj. R-squared:                  0.068
Method:                 Least Squares   F-statistic:                     29.23
Date:                Thu, 18 Aug 2022   Prob (F-statistic):           3.49e-87
Time:                        17:53:18   Log-Likelihood:                -1836.1
No. Observations:                9822   AIC:                             3706.
Df Residuals:                    9805   BIC:                             3828.
Df Model:                          16                                         
Covariance Type:                  HC3                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.1793      0.079      2.271      0.023       0.025       0.334
abuse         -0.0202      0.011     -1.871      0.061      -0.041       0.001
age            0.0160      0.003      5.123      0.000       0.010       0.022
agesq         -0.0002   3.86e-05     -5.986      0.000      -0.000      -0.000
educ           0.0369      0.008      4.778      0.000       0.022       0.052
educsq        -0.0009      0.000     -3.087      0.002      -0.001      -0.000
married        0.0574      0.010      5.623      0.000       0.037       0.077
famsize        0.0030      0.002      1.267      0.205      -0.002       0.008
white          0.0986      0.011      9.000      0.000       0.077       0.120
northeast      0.0166      0.009      1.825      0.068      -0.001       0.034
midwest        0.0047      0.009      0.536      0.592      -0.013       0.022
south          0.0152      0.009      1.774      0.076      -0.002       0.032
centcity      -0.0155      0.009     -1.759      0.079      -0.033       0.002
outercity      0.0149      0.008      1.954      0.051   -4.73e-05       0.030
qrt1          -0.0187      0.008     -2.238      0.025      -0.035      -0.002
qrt2          -0.0067      0.008     -0.818      0.413      -0.023       0.009
qrt3          -0.0016      0.008     -0.193      0.847      -0.018       0.015
==============================================================================
Omnibus:                     4507.768   Durbin-Watson:                   1.987
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            17498.631
Skew:                          -2.384   Prob(JB):                         0.00
Kurtosis:                       7.476   Cond. No.                     4.09e+04
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 4.09e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [96]:
model = sm.Probit(alcohol.employ, X, missing="drop").fit(cov_type="HC3")
model.summary()

Optimization terminated successfully.
         Current function value: 0.298295
         Iterations 6


<class 'statsmodels.iolib.summary.Summary'>
"""
                          Probit Regression Results                           
==============================================================================
Dep. Variable:                 employ   No. Observations:                 9822
Model:                         Probit   Df Residuals:                     9805
Method:                           MLE   Df Model:                           16
Date:                Thu, 18 Aug 2022   Pseudo R-squ.:                 0.09346
Time:                        17:53:19   Log-Likelihood:                -2929.9
converged:                       True   LL-Null:                       -3231.9
Covariance Type:                  HC3   LLR p-value:                3.110e-118
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -1.7628      0.378     -4.661      0.000      -2.504      -1.022
abuse         -0.1208      0.057     -2.126      0.033      -0.232      -0.009
age            0.0830      0.017      4.967      0.000       0.050       0.116
agesq         -0.0012      0.000     -6.013      0.000      -0.002      -0.001
educ           0.0827      0.028      2.962      0.003       0.028       0.138
educsq      -8.77e-05      0.001     -0.075      0.940      -0.002       0.002
married        0.3225      0.052      6.166      0.000       0.220       0.425
famsize        0.0213      0.014      1.539      0.124      -0.006       0.048
white          0.4595      0.046      9.942      0.000       0.369       0.550
northeast      0.1300      0.057      2.292      0.022       0.019       0.241
midwest        0.0575      0.052      1.098      0.272      -0.045       0.160
south          0.1038      0.051      2.041      0.041       0.004       0.203
centcity      -0.0700      0.050     -1.412      0.158      -0.167       0.027
outercity      0.1105      0.049      2.254      0.024       0.014       0.207
qrt1          -0.1079      0.051     -2.124      0.034      -0.207      -0.008
qrt2          -0.0463      0.051     -0.904      0.366      -0.147       0.054
qrt3          -0.0116      0.052     -0.222      0.825      -0.114       0.091
==============================================================================
"""

In [97]:
model.get_margeff().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
       Probit Marginal Effects       
=====================================
Dep. Variable:                 employ
Method:                          dydx
At:                           overall
==============================================================================
                dy/dx    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
abuse         -0.0195      0.009     -2.126      0.034      -0.037      -0.002
age            0.0134      0.003      4.961      0.000       0.008       0.019
agesq         -0.0002   3.23e-05     -6.004      0.000      -0.000      -0.000
educ           0.0134      0.005      2.964      0.003       0.005       0.022
educsq     -1.415e-05      0.000     -0.075      0.940      -0.000       0.000
married        0.0520      0.008      6.161      0.000       0.035       0.069
famsize        0.0034      0.002      1.539      0.124      -0.001       0.008
white          0.0741      0.007      9.937      0.000       0.060       0.089
northeast      0.0210      0.009      2.291      0.022       0.003       0.039
midwest        0.0093      0.008      1.098      0.272      -0.007       0.026
south          0.0167      0.008      2.041      0.041       0.001       0.033
centcity      -0.0113      0.008     -1.413      0.158      -0.027       0.004
outercity      0.0178      0.008      2.253      0.024       0.002       0.033
qrt1          -0.0174      0.008     -2.124      0.034      -0.033      -0.001
qrt2          -0.0075      0.008     -0.904      0.366      -0.024       0.009
qrt3          -0.0019      0.008     -0.222      0.825      -0.018       0.015
==============================================================================
"""

In [98]:
X = sm.add_constant(alcohol[["age", "agesq", "educ", "educsq", "married", "famsize", "white", "northeast", "midwest", "south", "centcity", "outercity", "qrt1", "qrt2", "qrt3"]])
model = IV2SLS(alcohol.employ, X, alcohol.abuse, alcohol[["mothalc", "fathalc"]]).fit(cov_type="robust")
model

IV-2SLS Estimation Summary                          
==============================================================================
Dep. Variable:                 employ   R-squared:                     -0.0387
Estimator:                    IV-2SLS   Adj. R-squared:                -0.0404
No. Observations:                9822   F-statistic:                    441.33
Date:                Thu, Aug 18 2022   P-value (F-stat)                0.0000
Time:                        17:53:19   Distribution:                 chi2(16)
Cov. Estimator:                robust                                         
                                                                              
                             Parameter Estimates                              
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
const          0.1732     0.0811     2.1347     0.0328      0.0142      0.3322
age            0.0178     0.0034     5.2495     0.0000      0.0112      0.0244
agesq         -0.0003  4.188e-05    -6.0293     0.0000     -0.0003     -0.0002
educ           0.0403     0.0079     5.0702     0.0000      0.0247      0.0558
educsq        -0.0011     0.0003    -3.5455     0.0004     -0.0017     -0.0005
married        0.0536     0.0106     5.0354     0.0000      0.0327      0.0745
famsize       -0.0013     0.0032    -0.4138     0.6790     -0.0076      0.0050
white          0.1059     0.0118     8.9414     0.0000      0.0827      0.1291
northeast      0.0170     0.0097     1.7459     0.0808     -0.0021      0.0361
midwest        0.0014     0.0095     0.1472     0.8830     -0.0172      0.0200
south          0.0125     0.0092     1.3611     0.1735     -0.0055      0.0305
centcity      -0.0072     0.0100    -0.7148     0.4747     -0.0268      0.0125
outercity      0.0184     0.0081     2.2597     0.0238      0.0024      0.0344
qrt1          -0.0181     0.0088    -2.0559     0.0398     -0.0354     -0.0008
qrt2          -0.0057     0.0087    -0.6553     0.5123     -0.0229      0.0114
qrt3          -0.0042     0.0087    -0.4847     0.6279     -0.0213      0.0129
abuse         -0.3546     0.1623    -2.1845     0.0289     -0.6727     -0.0364
==============================================================================

Endogenous: abuse
Instruments: mothalc, fathalc
Robust Covariance (Heteroskedastic)
Debiased: False
IVResults, id: 0x7fe46bf43d30

In [99]:
model.wooldridge_overid

Wooldridge's score test of overidentification
H0: Model is not overidentified.
Statistic: 0.4938
P-value: 0.4822
Distributed: chi2(1)
WaldTestStatistic, id: 0x7fe46bd63e20

C15.i 89.82% of the sample is employed. 9.92% have abused alcohol.

C15.ii Results above. Abuse is negatively associated with employment and is statistically significant at the 5% level. This would be in line with expectations.

C15.iii Results above. The Probit result for abuse is still negative and significant. The marginal effect is close but not identical to the linear model (-0.0283 vs. -0.0263).

C15.iv They are the same. this is likely because there is only one variable to work with.

C15.v Abuse is no longer significant at the 5% level (though it is at the 10% level). The magnitude is also a bit smaller (-0.0202).

C15.vi Results above. The APE is -0.0195 which is close but not identical. The coefficient is singificant.

C15.vii It seems like it would make sense to include the controls for overall health since alcohol abuse is associated with negative health outcomes.

C15.viii Alcoholism from parents seems to be associated with alcoholism in the child, but it may not be independent of the child's employment outcomes. If this is the case then it is not an appropriate IV for abuse.

C15.ix Results above. Abuse increases to -0.3546 and is significant at the 5% level. This is a very large effect and the largest we've seen by far.

C15.x We fail to reject the null hypothesis of exogeneity and so unless we feel particularly strongly about the objection in (viii), it would seem that these are good instruments.